[package]
name = 'node-primitives'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-system = { default-features = false, path = '../../../frame/system', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-application-crypto = { default-features = false, path = '../../../primitives/application-crypto', version = '6.0.0' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-system/std',
	'scale-info/std',
	'sp-application-crypto/std',
	'sp-core/std',
	'sp-runtime/std',
]
