[package]
name = 'beefy-gadget-rpc'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
repository = 'https://github.com/paritytech/substrate'
description = 'RPC for the BEEFY Client gadget for substrate'
homepage = 'https://substrate.io'

[dependencies]
beefy-gadget = { version = '4.0.0-dev', path = '../.' }
beefy-primitives = { version = '4.0.0-dev', path = '../../../primitives/beefy' }
codec = { version = '3.0.0', package = 'parity-scale-codec', features = ['derive'] }
futures = '0.3.21'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
jsonrpc-pubsub = '18.0.0'
log = '0.4'
parking_lot = '0.12.0'
sc-rpc = { version = '4.0.0-dev', path = '../../rpc' }
sc-utils = { version = '4.0.0-dev', path = '../../utils' }
serde = { version = '1.0.136', features = ['derive'] }
sp-core = { version = '6.0.0', path = '../../../primitives/core' }
sp-runtime = { version = '6.0.0', path = '../../../primitives/runtime' }
thiserror = '1.0'

[dev-dependencies]
sc-rpc = { version = '4.0.0-dev', path = '../../rpc', features = [
	'test-helpers',
] }
serde_json = '1.0.79'
substrate-test-runtime-client = { version = '2.0.0', path = '../../../test-utils/runtime/client' }
