[package]
name = 'beefy-gadget-rpc'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
repository = 'https://github.com/paritytech/substrate'
description = 'RPC for the BEEFY Client gadget for substrate'
homepage = 'https://substrate.io'

[dependencies]
beefy-gadget = { path = '../.', version = '4.0.0-dev' }
beefy-primitives = { path = '../../../primitives/beefy', version = '4.0.0-dev' }
codec = { features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
futures = '0.3.21'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
jsonrpc-pubsub = '18.0.0'
log = '0.4'
parking_lot = '0.12.0'
sc-rpc = { path = '../../rpc', version = '4.0.0-dev' }
sc-utils = { path = '../../utils', version = '4.0.0-dev' }
serde = { features = ['derive'], version = '1.0.136' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
thiserror = '1.0'

[dev-dependencies]
sc-rpc = { features = [
	'test-helpers',
], path = '../../rpc', version = '4.0.0-dev' }
serde_json = '1.0.79'
substrate-test-runtime-client = { path = '../../../test-utils/runtime/client', version = '2.0.0' }
