[package]
name = 'sc-executor-wasmi'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'This crate provides an implementation of `WasmRuntime` that is baked by wasmi.'
documentation = 'https://docs.rs/sc-executor-wasmi'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
log = '0.4.16'
sc-allocator = { path = '../../allocator', version = '4.1.0-dev' }
sc-executor-common = { path = '../common', version = '0.10.0-dev' }
sp-runtime-interface = { path = '../../../primitives/runtime-interface', version = '6.0.0' }
sp-sandbox = { path = '../../../primitives/sandbox', version = '0.10.0-dev' }
sp-wasm-interface = { path = '../../../primitives/wasm-interface', version = '6.0.0' }
wasmi = '0.9.1'
