[package]
name = 'node-testing'
version = '3.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Test utilities for Substrate node.'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = true

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
frame-system = { path = '../../../frame/system', version = '4.0.0-dev' }
fs_extra = '1'
futures = '0.3.21'
log = '0.4.16'
node-executor = { path = '../executor', version = '3.0.0-dev' }
node-primitives = { path = '../primitives', version = '2.0.0' }
node-runtime = { path = '../runtime', version = '3.0.0-dev' }
pallet-asset-tx-payment = { path = '../../../frame/transaction-payment/asset-tx-payment/', version = '4.0.0-dev' }
pallet-transaction-payment = { path = '../../../frame/transaction-payment', version = '4.0.0-dev' }
sc-block-builder = { path = '../../../client/block-builder', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api/', version = '4.0.0-dev' }
sc-client-db = { features = [
	'kvdb-rocksdb',
	'parity-db',
], path = '../../../client/db/', version = '0.10.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-executor = { features = [
	'wasmtime',
], path = '../../../client/executor', version = '0.10.0-dev' }
sc-service = { features = [
	'test-helpers',
	'db',
], path = '../../../client/service', version = '0.10.0-dev' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-block-builder = { path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }
sp-keyring = { path = '../../../primitives/keyring', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-timestamp = { default-features = false, path = '../../../primitives/timestamp', version = '4.0.0-dev' }
substrate-test-client = { path = '../../../test-utils/client', version = '2.0.0' }
tempfile = '3.1.0'
