[package]
name = 'substrate-test-utils-test-crate'
version = '0.1.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dev-dependencies]
sc-service = { path = '../../client/service', version = '0.10.0-dev' }
test-utils = { package = 'substrate-test-utils', path = '..', version = '4.0.0-dev' }
tokio = { features = ['macros'], version = '1.17.0' }
