[package]
name = 'sp-api-proc-macro'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Macros for declaring and implementing runtime apis.'
documentation = 'https://docs.rs/sp-api-proc-macro'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[lib]
proc-macro = true

[dependencies]
blake2 = { default-features = false, version = '0.10.2' }
proc-macro-crate = '1.1.3'
proc-macro2 = '1.0.37'
quote = '1.0.10'
syn = { features = ['full', 'fold', 'extra-traits', 'visit'], version = '1.0.82' }

[features]
default = [ 'std' ]
std = []
