[package]
name = 'pallet-election-provider-multi-phase'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'PALLET two phase election providers'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = [
	'derive',
] }
frame-benchmarking = { version = '4.0.0-dev', default-features = false, path = '../benchmarking', optional = true }
frame-election-provider-support = { version = '4.0.0-dev', default-features = false, path = '../election-provider-support' }
frame-support = { version = '4.0.0-dev', default-features = false, path = '../support' }
frame-system = { version = '4.0.0-dev', default-features = false, path = '../system' }
log = { version = '0.4.16', default-features = false }
pallet-election-provider-support-benchmarking = { version = '4.0.0-dev', default-features = false, path = '../election-provider-support/benchmarking', optional = true }
rand = { version = '0.7.3', default-features = false, optional = true, features = [
	'alloc',
	'small_rng',
] }
scale-info = { version = '2.0.1', default-features = false, features = [
	'derive',
] }
sp-arithmetic = { version = '5.0.0', default-features = false, path = '../../primitives/arithmetic' }
sp-core = { version = '6.0.0', default-features = false, path = '../../primitives/core' }
sp-io = { version = '6.0.0', default-features = false, path = '../../primitives/io' }
sp-npos-elections = { version = '4.0.0-dev', default-features = false, path = '../../primitives/npos-elections' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../../primitives/runtime' }
sp-std = { version = '4.0.0', default-features = false, path = '../../primitives/std' }
static_assertions = '1.1.0'
strum = { optional = true, default-features = false, version = '0.23.0', features = [
	'derive',
] }

[dev-dependencies]
frame-benchmarking = { version = '4.0.0-dev', path = '../benchmarking' }
pallet-balances = { version = '4.0.0-dev', path = '../balances' }
parking_lot = '0.12.0'
rand = { version = '0.7.3' }
sp-core = { version = '6.0.0', default-features = false, path = '../../primitives/core' }
sp-io = { version = '6.0.0', path = '../../primitives/io' }
sp-npos-elections = { version = '4.0.0-dev', default-features = false, path = '../../primitives/npos-elections' }
sp-tracing = { version = '5.0.0', path = '../../primitives/tracing' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'log/std',
	'rand/std',
	'scale-info/std',
	'sp-arithmetic/std',
	'sp-core/std',
	'sp-io/std',
	'sp-npos-elections/std',
	'sp-runtime/std',
	'sp-std/std',
	'strum/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-election-provider-support/runtime-benchmarks',
	'rand',
	'strum',
]
try-runtime = ['frame-support/try-runtime']
