[package]
name = 'pallet-election-provider-multi-phase'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'PALLET two phase election providers'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '../election-provider-support', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
log = { default-features = false, version = '0.4.16' }
pallet-election-provider-support-benchmarking = { default-features = false, optional = true, path = '../election-provider-support/benchmarking', version = '4.0.0-dev' }
rand = { default-features = false, features = [
	'alloc',
	'small_rng',
], optional = true, version = '0.7.3' }
scale-info = { default-features = false, features = [
	'derive',
], version = '2.0.1' }
sp-arithmetic = { default-features = false, path = '../../primitives/arithmetic', version = '5.0.0' }
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-npos-elections = { default-features = false, path = '../../primitives/npos-elections', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }
static_assertions = '1.1.0'
strum = { default-features = false, features = [
	'derive',
], optional = true, version = '0.23.0' }

[dev-dependencies]
frame-benchmarking = { path = '../benchmarking', version = '4.0.0-dev' }
pallet-balances = { path = '../balances', version = '4.0.0-dev' }
parking_lot = '0.12.0'
rand = { version = '0.7.3' }
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-io = { path = '../../primitives/io', version = '6.0.0' }
sp-npos-elections = { default-features = false, path = '../../primitives/npos-elections', version = '4.0.0-dev' }
sp-tracing = { path = '../../primitives/tracing', version = '5.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'log/std',
	'rand/std',
	'scale-info/std',
	'sp-arithmetic/std',
	'sp-core/std',
	'sp-io/std',
	'sp-npos-elections/std',
	'sp-runtime/std',
	'sp-std/std',
	'strum/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-election-provider-support/runtime-benchmarks',
	'rand',
	'strum',
]
try-runtime = ['frame-support/try-runtime']
