[package]
name = 'pallet-contracts-rpc'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Node-specific RPC methods for interaction with contracts.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
pallet-contracts-primitives = { path = '../common', version = '6.0.0' }
pallet-contracts-rpc-runtime-api = { path = './runtime-api', version = '4.0.0-dev' }
serde = { features = ['derive'], version = '1' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-rpc = { path = '../../../primitives/rpc', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }

[dev-dependencies]
serde_json = '1'
