[package]
name = 'pallet-election-provider-support-benchmarking'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Benchmarking for election provider support onchain config trait'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '..', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../system', version = '4.0.0-dev' }
sp-npos-elections = { default-features = false, path = '../../../primitives/npos-elections', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-system/std',
	'sp-npos-elections/std',
	'sp-runtime/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-election-provider-support/runtime-benchmarks',
]
