[package]
name = 'node-inspect'
version = '0.9.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
codec = { package = 'parity-scale-codec', version = '3.0.0' }
sc-cli = { path = '../../../client/cli', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-executor = { path = '../../../client/executor', version = '0.10.0-dev' }
sc-service = { default-features = false, path = '../../../client/service', version = '0.10.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
thiserror = '1.0'
