[package]
name = 'sp-state-machine'
version = '0.12.0'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Substrate State Machine'
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
documentation = 'https://docs.rs/sp-state-machine'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
hash-db = { default-features = false, version = '0.15.2' }
log = { optional = true, version = '0.4.16' }
num-traits = { default-features = false, version = '0.2.8' }
parking_lot = { optional = true, version = '0.12.0' }
rand = { optional = true, version = '0.7.2' }
smallvec = '1.8.0'
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-externalities = { default-features = false, path = '../externalities', version = '0.12.0' }
sp-panic-handler = { optional = true, path = '../panic-handler', version = '4.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-trie = { default-features = false, path = '../trie', version = '6.0.0' }
thiserror = { optional = true, version = '1.0.30' }
tracing = { optional = true, version = '0.1.29' }
trie-root = { default-features = false, version = '0.17.0' }

[dev-dependencies]
hex-literal = '0.3.4'
pretty_assertions = '1.0.0'
rand = '0.7.2'
sp-runtime = { path = '../runtime', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'hash-db/std',
	'log',
	'num-traits/std',
	'parking_lot',
	'rand',
	'sp-core/std',
	'sp-externalities/std',
	'sp-panic-handler',
	'sp-std/std',
	'sp-trie/std',
	'thiserror',
	'tracing',
	'trie-root/std',
]
