[package]
name = 'substrate-test-runtime'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
build = 'build.rs'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
beefy-primitives = { default-features = false, path = '../../primitives/beefy', version = '4.0.0-dev' }
cfg-if = '1.0'
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-support = { default-features = false, path = '../../frame/support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../frame/system', version = '4.0.0-dev' }
frame-system-rpc-runtime-api = { default-features = false, path = '../../frame/system/rpc/runtime-api', version = '4.0.0-dev' }
log = { default-features = false, version = '0.4.16' }
memory-db = { default-features = false, version = '0.29.0' }
pallet-babe = { default-features = false, path = '../../frame/babe', version = '4.0.0-dev' }
pallet-timestamp = { default-features = false, path = '../../frame/timestamp', version = '4.0.0-dev' }
parity-util-mem = { default-features = false, features = ['primitive-types'], version = '0.11.0' }
sc-service = { default-features = false, features = ['test-helpers'], optional = true, path = '../../client/service', version = '0.10.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-api = { default-features = false, path = '../../primitives/api', version = '4.0.0-dev' }
sp-application-crypto = { default-features = false, path = '../../primitives/application-crypto', version = '6.0.0' }
sp-block-builder = { default-features = false, path = '../../primitives/block-builder', version = '4.0.0-dev' }
sp-consensus-aura = { default-features = false, path = '../../primitives/consensus/aura', version = '0.10.0-dev' }
sp-consensus-babe = { default-features = false, path = '../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-externalities = { default-features = false, path = '../../primitives/externalities', version = '0.12.0' }
sp-finality-grandpa = { default-features = false, path = '../../primitives/finality-grandpa', version = '4.0.0-dev' }
sp-inherents = { default-features = false, path = '../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-keyring = { optional = true, path = '../../primitives/keyring', version = '6.0.0' }
sp-offchain = { default-features = false, path = '../../primitives/offchain', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-runtime-interface = { default-features = false, path = '../../primitives/runtime-interface', version = '6.0.0' }
sp-session = { default-features = false, path = '../../primitives/session', version = '4.0.0-dev' }
sp-state-machine = { default-features = false, path = '../../primitives/state-machine', version = '0.12.0' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }
sp-transaction-pool = { default-features = false, path = '../../primitives/transaction-pool', version = '4.0.0-dev' }
sp-trie = { default-features = false, path = '../../primitives/trie', version = '6.0.0' }
sp-version = { default-features = false, path = '../../primitives/version', version = '5.0.0' }
trie-db = { default-features = false, version = '0.23.1' }

[dev-dependencies]
futures = '0.3.21'
sc-block-builder = { path = '../../client/block-builder', version = '0.10.0-dev' }
sc-executor = { path = '../../client/executor', version = '0.10.0-dev' }
sp-consensus = { path = '../../primitives/consensus/common', version = '0.10.0-dev' }
substrate-test-runtime-client = { path = './client', version = '2.0.0' }

[build-dependencies]
substrate-wasm-builder = { version = '5.0.0-dev', path = '../../utils/wasm-builder' }

[features]
default = [
	'std',
]
std = [
	'beefy-primitives/std',
	'codec/std',
	'frame-support/std',
	'frame-system-rpc-runtime-api/std',
	'frame-system/std',
	'log/std',
	'memory-db/std',
	'pallet-babe/std',
	'pallet-timestamp/std',
	'sc-service',
	'scale-info/std',
	'serde',
	'sp-api/std',
	'sp-application-crypto/std',
	'sp-block-builder/std',
	'sp-consensus-aura/std',
	'sp-consensus-babe/std',
	'sp-core/std',
	'sp-core/std',
	'sp-externalities/std',
	'sp-finality-grandpa/std',
	'sp-inherents/std',
	'sp-io/std',
	'sp-keyring',
	'sp-offchain/std',
	'sp-runtime-interface/std',
	'sp-runtime/std',
	'sp-session/std',
	'sp-state-machine/std',
	'sp-std/std',
	'sp-transaction-pool/std',
	'sp-trie/std',
	'sp-version/std',
	'trie-db/std',
]
disable-logging = [ 'sp-api/disable-logging' ]
