[package]
name = 'substrate-test-runtime'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
build = 'build.rs'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
beefy-primitives = { version = '4.0.0-dev', default-features = false, path = '../../primitives/beefy' }
cfg-if = '1.0'
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = ['derive'] }
frame-support = { version = '4.0.0-dev', default-features = false, path = '../../frame/support' }
frame-system = { version = '4.0.0-dev', default-features = false, path = '../../frame/system' }
frame-system-rpc-runtime-api = { version = '4.0.0-dev', default-features = false, path = '../../frame/system/rpc/runtime-api' }
log = { version = '0.4.16', default-features = false }
memory-db = { version = '0.29.0', default-features = false }
pallet-babe = { version = '4.0.0-dev', default-features = false, path = '../../frame/babe' }
pallet-timestamp = { version = '4.0.0-dev', default-features = false, path = '../../frame/timestamp' }
parity-util-mem = { version = '0.11.0', default-features = false, features = ['primitive-types'] }
sc-service = { version = '0.10.0-dev', default-features = false, optional = true, features = ['test-helpers'], path = '../../client/service' }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
serde = { version = '1.0.136', optional = true, features = ['derive'] }
sp-api = { version = '4.0.0-dev', default-features = false, path = '../../primitives/api' }
sp-application-crypto = { version = '6.0.0', default-features = false, path = '../../primitives/application-crypto' }
sp-block-builder = { version = '4.0.0-dev', default-features = false, path = '../../primitives/block-builder' }
sp-consensus-aura = { version = '0.10.0-dev', default-features = false, path = '../../primitives/consensus/aura' }
sp-consensus-babe = { version = '0.10.0-dev', default-features = false, path = '../../primitives/consensus/babe' }
sp-core = { version = '6.0.0', default-features = false, path = '../../primitives/core' }
sp-externalities = { version = '0.12.0', default-features = false, path = '../../primitives/externalities' }
sp-finality-grandpa = { version = '4.0.0-dev', default-features = false, path = '../../primitives/finality-grandpa' }
sp-inherents = { version = '4.0.0-dev', default-features = false, path = '../../primitives/inherents' }
sp-io = { version = '6.0.0', default-features = false, path = '../../primitives/io' }
sp-keyring = { version = '6.0.0', optional = true, path = '../../primitives/keyring' }
sp-offchain = { version = '4.0.0-dev', default-features = false, path = '../../primitives/offchain' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../../primitives/runtime' }
sp-runtime-interface = { version = '6.0.0', default-features = false, path = '../../primitives/runtime-interface' }
sp-session = { version = '4.0.0-dev', default-features = false, path = '../../primitives/session' }
sp-state-machine = { version = '0.12.0', default-features = false, path = '../../primitives/state-machine' }
sp-std = { version = '4.0.0', default-features = false, path = '../../primitives/std' }
sp-transaction-pool = { version = '4.0.0-dev', default-features = false, path = '../../primitives/transaction-pool' }
sp-trie = { version = '6.0.0', default-features = false, path = '../../primitives/trie' }
sp-version = { version = '5.0.0', default-features = false, path = '../../primitives/version' }
trie-db = { version = '0.23.1', default-features = false }

[dev-dependencies]
futures = '0.3.21'
sc-block-builder = { version = '0.10.0-dev', path = '../../client/block-builder' }
sc-executor = { version = '0.10.0-dev', path = '../../client/executor' }
sp-consensus = { version = '0.10.0-dev', path = '../../primitives/consensus/common' }
substrate-test-runtime-client = { version = '2.0.0', path = './client' }

[build-dependencies]
substrate-wasm-builder = { version = '5.0.0-dev', path = '../../utils/wasm-builder' }

[features]
default = [
	'std',
]
std = [
	'beefy-primitives/std',
	'codec/std',
	'frame-support/std',
	'frame-system-rpc-runtime-api/std',
	'frame-system/std',
	'log/std',
	'memory-db/std',
	'pallet-babe/std',
	'pallet-timestamp/std',
	'sc-service',
	'scale-info/std',
	'serde',
	'sp-api/std',
	'sp-application-crypto/std',
	'sp-block-builder/std',
	'sp-consensus-aura/std',
	'sp-consensus-babe/std',
	'sp-core/std',
	'sp-core/std',
	'sp-externalities/std',
	'sp-finality-grandpa/std',
	'sp-inherents/std',
	'sp-io/std',
	'sp-keyring',
	'sp-offchain/std',
	'sp-runtime-interface/std',
	'sp-runtime/std',
	'sp-session/std',
	'sp-state-machine/std',
	'sp-std/std',
	'sp-transaction-pool/std',
	'sp-trie/std',
	'sp-version/std',
	'trie-db/std',
]
disable-logging = [ 'sp-api/disable-logging' ]
