[package]
name = 'remote-externalities'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'An externalities provided environemnt that can load itself from remote nodes or cache files'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
env_logger = '0.9'
frame-support = { optional = true, path = '../../../frame/support', version = '4.0.0-dev' }
jsonrpsee = { features = ['ws-client', 'macros'], version = '0.10.1' }
log = '0.4.16'
serde = '1.0.136'
serde_json = '1.0'
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-version = { path = '../../../primitives/version', version = '5.0.0' }

[dev-dependencies]
frame-support = { path = '../../../frame/support', version = '4.0.0-dev' }
pallet-elections-phragmen = { path = '../../../frame/elections-phragmen', version = '5.0.0-dev' }
tokio = { features = ['macros', 'rt-multi-thread'], version = '1.17.0' }

[features]
remote-test = ['frame-support']
