[package]
name = 'sp-keyring'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Keyring support code for the runtime. A set of test accounts.'
documentation = 'https://docs.rs/sp-keyring'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
lazy_static = '1.4.0'
sp-core = { path = '../core', version = '6.0.0' }
sp-runtime = { path = '../runtime', version = '6.0.0' }
strum = { features = ['derive'], version = '0.23.0' }
