[package]
name = 'substrate-frame-rpc-system'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = "FRAME's system exposed over Substrate RPC"
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
frame-system-rpc-runtime-api = { path = '../../../../frame/system/rpc/runtime-api', version = '4.0.0-dev' }
futures = '0.3.21'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
log = '0.4.16'
sc-client-api = { path = '../../../../client/api', version = '4.0.0-dev' }
sc-rpc-api = { path = '../../../../client/rpc-api', version = '0.10.0-dev' }
sc-transaction-pool-api = { path = '../../../../client/transaction-pool/api', version = '4.0.0-dev' }
sp-api = { path = '../../../../primitives/api', version = '4.0.0-dev' }
sp-block-builder = { path = '../../../../primitives/block-builder', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../../primitives/blockchain', version = '4.0.0-dev' }
sp-core = { path = '../../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../../primitives/runtime', version = '6.0.0' }

[dev-dependencies]
sc-transaction-pool = { path = '../../../../client/transaction-pool', version = '4.0.0-dev' }
sp-tracing = { path = '../../../../primitives/tracing', version = '5.0.0' }
substrate-test-runtime-client = { path = '../../../../test-utils/runtime/client', version = '2.0.0' }
