[package]
name = 'sp-runtime-interface-test-wasm'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
build = 'build.rs'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
sp-core = { default-features = false, path = '../../core', version = '6.0.0' }
sp-io = { default-features = false, path = '../../io', version = '6.0.0' }
sp-runtime-interface = { default-features = false, path = '../', version = '6.0.0' }
sp-std = { default-features = false, path = '../../std', version = '4.0.0' }

[build-dependencies]
substrate-wasm-builder = { version = '5.0.0-dev', path = '../../../utils/wasm-builder' }

[features]
default = [ 'std' ]
std = [ 'sp-core/std', 'sp-io/std', 'sp-runtime-interface/std', 'sp-std/std' ]
