[package]
name = 'beefy-merkle-tree'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
repository = 'https://github.com/paritytech/substrate'
description = 'A no-std/Substrate compatible library to construct binary merkle tree.'
homepage = 'https://substrate.io'

[dependencies]
hex = { default-features = false, optional = true, version = '0.4' }
log = { default-features = false, optional = true, version = '0.4' }
tiny-keccak = { features = ['keccak'], optional = true, version = '2.0.2' }

[dev-dependencies]
env_logger = '0.9'
hex = '0.4'
hex-literal = '0.3'

[features]
debug = ['hex', 'hex/std', 'log']
default = ['debug', 'keccak', 'std']
keccak = ['tiny-keccak']
std = []
