[package]
name = 'substrate-frame-rpc-support'
version = '3.0.0'
authors = [
	'Parity Technologies <admin@parity.io>',
	'Andrew Dirksen <andrew@dirksen.com>',
]
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = "Substrate RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
frame-support = { path = '../../../../frame/support', version = '4.0.0-dev' }
futures = '0.3.21'
jsonrpc-client-transports = { features = ['http'], version = '18.0.0' }
sc-rpc-api = { path = '../../../../client/rpc-api', version = '0.10.0-dev' }
serde = '1'
sp-storage = { path = '../../../../primitives/storage', version = '6.0.0' }

[dev-dependencies]
frame-system = { path = '../../../../frame/system', version = '4.0.0-dev' }
scale-info = '2.0.1'
tokio = '1.17.0'
