[package]
name = 'frame-election-solution-type-fuzzer'
version = '2.0.0-alpha.5'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Fuzzer for phragmén solution type implementation.'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
clap = { features = ['derive'], version = '3.0' }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-election-provider-solution-type = { path = '..', version = '4.0.0-dev' }
frame-election-provider-support = { path = '../..', version = '4.0.0-dev' }
frame-support = { path = '../../../support', version = '4.0.0-dev' }
honggfuzz = '0.5'
rand = { features = ['std', 'small_rng'], version = '0.8' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-arithmetic = { path = '../../../../primitives/arithmetic', version = '5.0.0' }
sp-npos-elections = { default-features = false, path = '../../../../primitives/npos-elections', version = '4.0.0-dev' }
sp-runtime = { path = '../../../../primitives/runtime', version = '6.0.0' }

[[bin]]
name = 'compact'
path = 'src/compact.rs'
