[package]
name = 'chain-spec-builder'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
build = 'build.rs'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
ansi_term = '0.12.1'
clap = { features = ['derive'], version = '3.1.6' }
node-cli = { path = '../../node/cli', version = '3.0.0-dev' }
rand = '0.8'
sc-chain-spec = { path = '../../../client/chain-spec', version = '4.0.0-dev' }
sc-keystore = { path = '../../../client/keystore', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-keystore = { path = '../../../primitives/keystore', version = '0.12.0' }
