[package]
name = 'pallet-asset-tx-payment'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'pallet to manage transaction payments in assets'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = ['derive'] }
frame-support = { version = '4.0.0-dev', default-features = false, path = '../../support' }
frame-system = { version = '4.0.0-dev', default-features = false, path = '../../system' }
pallet-transaction-payment = { version = '4.0.0-dev', default-features = false, path = '..' }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
serde = { version = '1.0.136', optional = true }
sp-core = { version = '6.0.0', default-features = false, path = '../../../primitives/core' }
sp-io = { version = '6.0.0', default-features = false, path = '../../../primitives/io' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../../../primitives/runtime' }
sp-std = { version = '4.0.0', default-features = false, path = '../../../primitives/std' }

[dev-dependencies]
pallet-assets = { version = '4.0.0-dev', path = '../../assets' }
pallet-authorship = { version = '4.0.0-dev', path = '../../authorship' }
pallet-balances = { version = '4.0.0-dev', path = '../../balances' }
serde_json = '1.0.79'
smallvec = '1.8.0'
sp-storage = { version = '6.0.0', default-features = false, path = '../../../primitives/storage' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-transaction-payment/std',
	'serde',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
try-runtime = ['frame-support/try-runtime']
