[package]
name = 'pallet-asset-tx-payment'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'pallet to manage transaction payments in assets'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-support = { default-features = false, path = '../../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../system', version = '4.0.0-dev' }
pallet-transaction-payment = { default-features = false, path = '..', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { optional = true, version = '1.0.136' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-io = { default-features = false, path = '../../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }

[dev-dependencies]
pallet-assets = { path = '../../assets', version = '4.0.0-dev' }
pallet-authorship = { path = '../../authorship', version = '4.0.0-dev' }
pallet-balances = { path = '../../balances', version = '4.0.0-dev' }
serde_json = '1.0.79'
smallvec = '1.8.0'
sp-storage = { default-features = false, path = '../../../primitives/storage', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-transaction-payment/std',
	'serde',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
try-runtime = ['frame-support/try-runtime']
