[package]
name = 'pallet-staking'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet staking'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '../election-provider-support', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
log = { default-features = false, version = '0.4.16' }
pallet-authorship = { default-features = false, path = '../authorship', version = '4.0.0-dev' }
pallet-session = { default-features = false, features = [
	'historical',
], path = '../session', version = '4.0.0-dev' }
rand_chacha = { default-features = false, optional = true, version = '0.2' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { optional = true, version = '1.0.136' }
sp-application-crypto = { default-features = false, path = '../../primitives/application-crypto', version = '6.0.0' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-staking = { default-features = false, path = '../../primitives/staking', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }

[dev-dependencies]
frame-benchmarking = { path = '../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { path = '../election-provider-support', version = '4.0.0-dev' }
pallet-bags-list = { features = ['runtime-benchmarks'], path = '../bags-list', version = '4.0.0-dev' }
pallet-balances = { path = '../balances', version = '4.0.0-dev' }
pallet-staking-reward-curve = { path = '../staking/reward-curve', version = '4.0.0-dev' }
pallet-timestamp = { path = '../timestamp', version = '4.0.0-dev' }
rand_chacha = { version = '0.2' }
sp-core = { path = '../../primitives/core', version = '6.0.0' }
sp-npos-elections = { path = '../../primitives/npos-elections', version = '4.0.0-dev' }
sp-tracing = { path = '../../primitives/tracing', version = '5.0.0' }
substrate-test-utils = { path = '../../test-utils', version = '4.0.0-dev' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'pallet-authorship/std',
	'pallet-session/std',
	'scale-info/std',
	'serde',
	'sp-application-crypto/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-election-provider-support/runtime-benchmarks',
	'rand_chacha',
	'sp-staking/runtime-benchmarks',
]
try-runtime = ['frame-support/try-runtime']
