[package]
name = 'pallet-staking'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet staking'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = [
	'derive',
] }
frame-benchmarking = { version = '4.0.0-dev', default-features = false, path = '../benchmarking', optional = true }
frame-election-provider-support = { version = '4.0.0-dev', default-features = false, path = '../election-provider-support' }
frame-support = { version = '4.0.0-dev', default-features = false, path = '../support' }
frame-system = { version = '4.0.0-dev', default-features = false, path = '../system' }
log = { version = '0.4.16', default-features = false }
pallet-authorship = { version = '4.0.0-dev', default-features = false, path = '../authorship' }
pallet-session = { version = '4.0.0-dev', default-features = false, features = [
	'historical',
], path = '../session' }
rand_chacha = { version = '0.2', default-features = false, optional = true }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
serde = { version = '1.0.136', optional = true }
sp-application-crypto = { version = '6.0.0', default-features = false, path = '../../primitives/application-crypto' }
sp-io = { version = '6.0.0', default-features = false, path = '../../primitives/io' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../../primitives/runtime' }
sp-staking = { version = '4.0.0-dev', default-features = false, path = '../../primitives/staking' }
sp-std = { version = '4.0.0', default-features = false, path = '../../primitives/std' }

[dev-dependencies]
frame-benchmarking = { version = '4.0.0-dev', path = '../benchmarking' }
frame-election-provider-support = { version = '4.0.0-dev', path = '../election-provider-support' }
pallet-bags-list = { version = '4.0.0-dev', features = ['runtime-benchmarks'], path = '../bags-list' }
pallet-balances = { version = '4.0.0-dev', path = '../balances' }
pallet-staking-reward-curve = { version = '4.0.0-dev', path = '../staking/reward-curve' }
pallet-timestamp = { version = '4.0.0-dev', path = '../timestamp' }
rand_chacha = { version = '0.2' }
sp-core = { version = '6.0.0', path = '../../primitives/core' }
sp-npos-elections = { version = '4.0.0-dev', path = '../../primitives/npos-elections' }
sp-tracing = { version = '5.0.0', path = '../../primitives/tracing' }
substrate-test-utils = { version = '4.0.0-dev', path = '../../test-utils' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'pallet-authorship/std',
	'pallet-session/std',
	'scale-info/std',
	'serde',
	'sp-application-crypto/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-election-provider-support/runtime-benchmarks',
	'rand_chacha',
	'sp-staking/runtime-benchmarks',
]
try-runtime = ['frame-support/try-runtime']
