[package]
name = 'node-cli'
version = '3.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Generic Substrate node implementation in Rust.'
build = 'build.rs'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
default-run = 'substrate'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[badges]
travis-ci = { repository = 'paritytech/substrate' }
maintenance = { status = 'actively-developed' }
is-it-maintained-issue-resolution = { repository = 'paritytech/substrate' }
is-it-maintained-open-issues = { repository = 'paritytech/substrate' }

[[bin]]
name = 'substrate'
path = 'bin/main.rs'
required-features = ['cli']

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
clap = { features = ['derive'], optional = true, version = '3.1.6' }
codec = { package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking-cli = { optional = true, path = '../../../utils/frame/benchmarking-cli', version = '4.0.0-dev' }
frame-system = { path = '../../../frame/system', version = '4.0.0-dev' }
frame-system-rpc-runtime-api = { path = '../../../frame/system/rpc/runtime-api', version = '4.0.0-dev' }
futures = '0.3.21'
grandpa = { package = 'sc-finality-grandpa', path = '../../../client/finality-grandpa', version = '0.10.0-dev' }
grandpa-primitives = { package = 'sp-finality-grandpa', path = '../../../primitives/finality-grandpa', version = '4.0.0-dev' }
hex-literal = '0.3.4'
log = '0.4.16'
node-executor = { path = '../executor', version = '3.0.0-dev' }
node-inspect = { optional = true, path = '../inspect', version = '0.9.0-dev' }
node-primitives = { path = '../primitives', version = '2.0.0' }
node-rpc = { path = '../rpc', version = '3.0.0-dev' }
node-runtime = { path = '../runtime', version = '3.0.0-dev' }
pallet-asset-tx-payment = { path = '../../../frame/transaction-payment/asset-tx-payment/', version = '4.0.0-dev' }
pallet-im-online = { default-features = false, path = '../../../frame/im-online', version = '4.0.0-dev' }
pallet-transaction-payment = { path = '../../../frame/transaction-payment', version = '4.0.0-dev' }
rand = '0.8'
sc-authority-discovery = { path = '../../../client/authority-discovery', version = '0.10.0-dev' }
sc-basic-authorship = { path = '../../../client/basic-authorship', version = '0.10.0-dev' }
sc-chain-spec = { path = '../../../client/chain-spec', version = '4.0.0-dev' }
sc-cli = { optional = true, path = '../../../client/cli', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-consensus-babe = { path = '../../../client/consensus/babe', version = '0.10.0-dev' }
sc-consensus-slots = { path = '../../../client/consensus/slots', version = '0.10.0-dev' }
sc-consensus-uncles = { path = '../../../client/consensus/uncles', version = '0.10.0-dev' }
sc-executor = { path = '../../../client/executor', version = '0.10.0-dev' }
sc-network = { path = '../../../client/network', version = '0.10.0-dev' }
sc-rpc = { path = '../../../client/rpc', version = '4.0.0-dev' }
sc-service = { default-features = false, path = '../../../client/service', version = '0.10.0-dev' }
sc-sync-state-rpc = { path = '../../../client/sync-state-rpc', version = '0.10.0-dev' }
sc-sysinfo = { path = '../../../client/sysinfo', version = '6.0.0-dev' }
sc-telemetry = { path = '../../../client/telemetry', version = '4.0.0-dev' }
sc-transaction-pool = { path = '../../../client/transaction-pool', version = '4.0.0-dev' }
sc-transaction-pool-api = { path = '../../../client/transaction-pool/api', version = '4.0.0-dev' }
serde = { features = ['derive'], version = '1.0.136' }
serde_json = '1.0.79'
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-authority-discovery = { path = '../../../primitives/authority-discovery', version = '4.0.0-dev' }
sp-authorship = { path = '../../../primitives/authorship', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-babe = { path = '../../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-keyring = { path = '../../../primitives/keyring', version = '6.0.0' }
sp-keystore = { path = '../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-timestamp = { path = '../../../primitives/timestamp', version = '4.0.0-dev' }
sp-transaction-pool = { path = '../../../primitives/transaction-pool', version = '4.0.0-dev' }
sp-transaction-storage-proof = { path = '../../../primitives/transaction-storage-proof', version = '4.0.0-dev' }
try-runtime-cli = { optional = true, path = '../../../utils/frame/try-runtime/cli', version = '0.10.0-dev' }

[target.'cfg(any(target_arch="x86_64", target_arch="aarch64"))'.dependencies]
node-executor = { version = '3.0.0-dev', path = '../executor', features = ['wasmtime'] }
sc-cli = { version = '0.10.0-dev', optional = true, path = '../../../client/cli', features = ['wasmtime'] }
sc-service = { version = '0.10.0-dev', default-features = false, path = '../../../client/service', features = [
	'wasmtime',
] }
sp-trie = { version = '6.0.0', default-features = false, path = '../../../primitives/trie', features = [
	'memory-tracker',
] }

[dev-dependencies]
assert_cmd = '2.0.2'
async-std = { features = ['attributes'], version = '1.11.0' }
criterion = { features = ['async_tokio'], version = '0.3.5' }
futures = '0.3.21'
nix = '0.23'
pallet-timestamp = { path = '../../../frame/timestamp', version = '4.0.0-dev' }
platforms = '2.0'
regex = '1.5.5'
remote-externalities = { path = '../../../utils/frame/remote-externalities' }
sc-block-builder = { path = '../../../client/block-builder', version = '0.10.0-dev' }
sc-client-db = { path = '../../../client/db', version = '0.10.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-consensus-babe = { path = '../../../client/consensus/babe', version = '0.10.0-dev' }
sc-consensus-epochs = { path = '../../../client/consensus/epochs', version = '0.10.0-dev' }
sc-keystore = { path = '../../../client/keystore', version = '4.0.0-dev' }
sc-service-test = { path = '../../../client/service/test', version = '2.0.0' }
serde_json = '1.0'
soketto = '0.7.1'
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-tracing = { path = '../../../primitives/tracing', version = '5.0.0' }
tempfile = '3.1.0'
tokio = { features = ['macros', 'time', 'parking_lot'], version = '1.17.0' }
wait-timeout = '0.2'

[build-dependencies]
clap = { version = '3.1.6', optional = true }
clap_complete = { version = '3.0', optional = true }
node-inspect = { version = '0.9.0-dev', optional = true, path = '../inspect' }
frame-benchmarking-cli = { version = '4.0.0-dev', optional = true, path = '../../../utils/frame/benchmarking-cli' }
substrate-build-script-utils = { version = '3.0.0', optional = true, path = '../../../utils/build-script-utils' }
substrate-frame-cli = { version = '4.0.0-dev', optional = true, path = '../../../utils/frame/frame-utilities-cli' }
try-runtime-cli = { version = '0.10.0-dev', optional = true, path = '../../../utils/frame/try-runtime/cli' }
sc-cli = { version = '0.10.0-dev', path = '../../../client/cli', optional = true }
pallet-balances = { version = '4.0.0-dev', path = '../../../frame/balances' }

[features]
default = ['cli']
cli = [
	'clap',
	'clap_complete',
	'frame-benchmarking-cli',
	'node-executor/wasmi-errno',
	'node-inspect',
	'sc-cli',
	'sc-service/db',
	'substrate-build-script-utils',
	'substrate-frame-cli',
	'try-runtime-cli',
]
runtime-benchmarks = ['frame-benchmarking-cli', 'node-runtime/runtime-benchmarks']
try-runtime = ['node-runtime/try-runtime', 'try-runtime-cli']

[[bench]]
name = 'transaction_pool'
harness = false

[[bench]]
name = 'block_production'
harness = false
