[package]
name = 'try-runtime-cli'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Cli command runtime testing and dry-running'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
jsonrpsee = { default-features = false, features = ['ws-client'], version = '0.10.1' }
log = '0.4.16'
parity-scale-codec = '3.0.0'
remote-externalities = { path = '../../remote-externalities', version = '0.10.0-dev' }
sc-chain-spec = { path = '../../../../client/chain-spec', version = '4.0.0-dev' }
sc-cli = { path = '../../../../client/cli', version = '0.10.0-dev' }
sc-executor = { path = '../../../../client/executor', version = '0.10.0-dev' }
sc-service = { default-features = false, path = '../../../../client/service', version = '0.10.0-dev' }
serde = '1.0.136'
sp-core = { path = '../../../../primitives/core', version = '6.0.0' }
sp-externalities = { path = '../../../../primitives/externalities', version = '0.12.0' }
sp-io = { path = '../../../../primitives/io', version = '6.0.0' }
sp-keystore = { path = '../../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../../primitives/runtime', version = '6.0.0' }
sp-state-machine = { path = '../../../../primitives/state-machine', version = '0.12.0' }
sp-version = { path = '../../../../primitives/version', version = '5.0.0' }
zstd = { default-features = false, version = '0.10.0' }
