[package]
name = 'sp-runtime-interface'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Substrate runtime interface'
documentation = 'https://docs.rs/sp-runtime-interface/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
impl-trait-for-tuples = '0.2.2'
primitive-types = { default-features = false, version = '0.11.1' }
sp-externalities = { optional = true, path = '../externalities', version = '0.12.0' }
sp-runtime-interface-proc-macro = { path = 'proc-macro', version = '5.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-storage = { default-features = false, path = '../storage', version = '6.0.0' }
sp-tracing = { default-features = false, path = '../tracing', version = '5.0.0' }
sp-wasm-interface = { default-features = false, path = '../wasm-interface', version = '6.0.0' }
static_assertions = '1.0.0'

[dev-dependencies]
rustversion = '1.0.6'
sp-core = { path = '../core', version = '6.0.0' }
sp-io = { path = '../io', version = '6.0.0' }
sp-runtime-interface-test-wasm = { path = 'test-wasm', version = '2.0.0' }
sp-state-machine = { path = '../state-machine', version = '0.12.0' }
trybuild = '1.0.60'

[features]
default = [ 'std' ]
std = [
	'codec/std',
	'primitive-types/std',
	'sp-externalities',
	'sp-std/std',
	'sp-tracing/std',
	'sp-wasm-interface/std',
]
disable_target_static_assertions = []
