[package]
name = 'sp-io'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'I/O for Substrate runtimes'
documentation = 'https://docs.rs/sp-io'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }
futures = { version = '0.3.21', features = ['thread-pool'], optional = true }
hash-db = { version = '0.15.2', default-features = false }
libsecp256k1 = { version = '0.7', optional = true }
log = { version = '0.4.16', optional = true }
parking_lot = { version = '0.12.0', optional = true }
secp256k1 = { version = '0.21.2', features = ['recovery', 'global-context'], optional = true }
sp-core = { version = '6.0.0', default-features = false, path = '../core' }
sp-externalities = { version = '0.12.0', optional = true, path = '../externalities' }
sp-keystore = { version = '0.12.0', default-features = false, optional = true, path = '../keystore' }
sp-runtime-interface = { version = '6.0.0', default-features = false, path = '../runtime-interface' }
sp-state-machine = { version = '0.12.0', optional = true, path = '../state-machine' }
sp-std = { version = '4.0.0', default-features = false, path = '../std' }
sp-tracing = { version = '5.0.0', default-features = false, path = '../tracing' }
sp-trie = { version = '6.0.0', optional = true, path = '../trie' }
sp-wasm-interface = { version = '6.0.0', path = '../wasm-interface', default-features = false }
tracing = { version = '0.1.29', default-features = false }
tracing-core = { version = '0.1.26', default-features = false }

[features]
default = ['std']
std = [
	'codec/std',
	'futures',
	'hash-db/std',
	'libsecp256k1',
	'log',
	'parking_lot',
	'secp256k1',
	'sp-core/std',
	'sp-externalities',
	'sp-keystore',
	'sp-runtime-interface/std',
	'sp-state-machine',
	'sp-std/std',
	'sp-tracing/std',
	'sp-trie',
	'sp-wasm-interface/std',
	'tracing-core/std',
	'tracing/std',
]
with-tracing = [
	'sp-tracing/with-tracing',
]
disable_panic_handler = []
disable_oom = []
disable_allocator = []
improved_panic_error_reporting = []
