[package]
name = 'sp-io'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'I/O for Substrate runtimes'
documentation = 'https://docs.rs/sp-io'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
futures = { features = ['thread-pool'], optional = true, version = '0.3.21' }
hash-db = { default-features = false, version = '0.15.2' }
libsecp256k1 = { optional = true, version = '0.7' }
log = { optional = true, version = '0.4.16' }
parking_lot = { optional = true, version = '0.12.0' }
secp256k1 = { features = ['recovery', 'global-context'], optional = true, version = '0.21.2' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-externalities = { optional = true, path = '../externalities', version = '0.12.0' }
sp-keystore = { default-features = false, optional = true, path = '../keystore', version = '0.12.0' }
sp-runtime-interface = { default-features = false, path = '../runtime-interface', version = '6.0.0' }
sp-state-machine = { optional = true, path = '../state-machine', version = '0.12.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-tracing = { default-features = false, path = '../tracing', version = '5.0.0' }
sp-trie = { optional = true, path = '../trie', version = '6.0.0' }
sp-wasm-interface = { default-features = false, path = '../wasm-interface', version = '6.0.0' }
tracing = { default-features = false, version = '0.1.29' }
tracing-core = { default-features = false, version = '0.1.26' }

[features]
default = ['std']
std = [
	'codec/std',
	'futures',
	'hash-db/std',
	'libsecp256k1',
	'log',
	'parking_lot',
	'secp256k1',
	'sp-core/std',
	'sp-externalities',
	'sp-keystore',
	'sp-runtime-interface/std',
	'sp-state-machine',
	'sp-std/std',
	'sp-tracing/std',
	'sp-trie',
	'sp-wasm-interface/std',
	'tracing-core/std',
	'tracing/std',
]
with-tracing = [
	'sp-tracing/with-tracing',
]
disable_panic_handler = []
disable_oom = []
disable_allocator = []
improved_panic_error_reporting = []
