[package]
name = 'sp-core-hashing'
version = '4.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Primitive core crate hashing implementation.'
documentation = 'https://docs.rs/sp-core-hashing'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
blake2 = { default-features = false, version = '0.10.2' }
byteorder = { default-features = false, version = '1.3.2' }
digest = { default-features = false, version = '0.10.3' }
sha2 = { default-features = false, version = '0.10.2' }
sha3 = { default-features = false, version = '0.10.0' }
sp-std = { default-features = false, path = '../../std', version = '4.0.0' }
twox-hash = { default-features = false, features = ['digest_0_10'], version = '1.6.2' }

[features]
default = ['std']
std = [
	'blake2/std',
	'sha2/std',
	'sha3/std',
	'sp-std/std',
	'twox-hash/std',
]
