[package]
name = 'sp-staking'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'A crate which contains primitives that are useful for implementation that uses staking approaches in general. Definitions related to sessions, slashing, etc go here.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'sp-runtime/std',
	'sp-std/std',
]
runtime-benchmarks = []
