[package]
name = 'sc-executor-wasmtime'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Defines a `WasmRuntime` that uses the Wasmtime JIT to execute.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
cfg-if = '1.0'
codec = { package = 'parity-scale-codec', version = '3.0.0' }
libc = '0.2.121'
log = '0.4.16'
parity-wasm = '0.42.0'
sc-allocator = { path = '../../allocator', version = '4.1.0-dev' }
sc-executor-common = { path = '../common', version = '0.10.0-dev' }
sp-runtime-interface = { path = '../../../primitives/runtime-interface', version = '6.0.0' }
sp-sandbox = { path = '../../../primitives/sandbox', version = '0.10.0-dev' }
sp-wasm-interface = { features = ['wasmtime'], path = '../../../primitives/wasm-interface', version = '6.0.0' }
wasmtime = { default-features = false, features = [
	'cache',
	'cranelift',
	'jitdump',
	'parallel-compilation',
], version = '0.35.3' }

[dev-dependencies]
sc-runtime-test = { path = '../runtime-test', version = '2.0.0' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }
wat = '1.0'
