[package]
name = 'pallet-nomination-pools-benchmarking'
version = '1.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME nomination pools pallet benchmarking'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, path = '../../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '../../election-provider-support', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../system', version = '4.0.0-dev' }
pallet-bags-list = { default-features = false, features = ['runtime-benchmarks'], path = '../../bags-list', version = '4.0.0-dev' }
pallet-nomination-pools = { default-features = false, features = ['runtime-benchmarks'], path = '../', version = '1.0.0' }
pallet-staking = { default-features = false, features = ['runtime-benchmarks'], path = '../../staking', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-staking = { default-features = false, path = '../../../primitives/staking', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }

[dev-dependencies]
pallet-balances = { default-features = false, path = '../../balances', version = '4.0.0-dev' }
pallet-staking-reward-curve = { path = '../../staking/reward-curve', version = '4.0.0-dev' }
pallet-timestamp = { path = '../../timestamp', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }

[features]
default = ['std']
std = [
	'frame-benchmarking/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-bags-list/std',
	'pallet-balances/std',
	'pallet-nomination-pools/std',
	'pallet-staking/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
