[package]
name = 'pallet-nomination-pools'
version = '1.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME nomination pools pallet'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = ['derive'] }
frame-support = { version = '4.0.0-dev', default-features = false, path = '../support' }
frame-system = { version = '4.0.0-dev', default-features = false, path = '../system' }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
sp-core = { version = '6.0.0', default-features = false, path = '../../primitives/core' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../../primitives/runtime' }
sp-staking = { version = '4.0.0-dev', default-features = false, path = '../../primitives/staking' }
sp-std = { version = '4.0.0', default-features = false, path = '../../primitives/std' }

[dev-dependencies]
pallet-balances = { version = '4.0.0-dev', path = '../balances' }
sp-io = { version = '6.0.0', path = '../../primitives/io' }
sp-tracing = { version = '5.0.0', path = '../../primitives/tracing' }

[features]
runtime-benchmarks = []
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'scale-info/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
