[package]
description = 'Substrate offchain workers primitives'
name = 'sp-offchain'
version = '4.0.0-dev'
license = 'Apache-2.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
sp-api = { default-features = false, path = '../api', version = '4.0.0-dev' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }

[features]
default = ['std']
std = ['sp-api/std', 'sp-core/std', 'sp-runtime/std']
