[package]
name = 'sp-externalities'
version = '0.12.0'
license = 'Apache-2.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Substrate externalities abstraction'
documentation = 'https://docs.rs/sp-externalities'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
environmental = { default-features = false, version = '1.1.3' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-storage = { default-features = false, path = '../storage', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'environmental/std',
	'sp-std/std',
	'sp-storage/std',
]
