[package]
name = 'sp-tasks'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Runtime asynchronous, pure computational tasks'
documentation = 'https://docs.rs/sp-tasks'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
log = { optional = true, version = '0.4.16' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-externalities = { optional = true, path = '../externalities', version = '0.12.0' }
sp-io = { default-features = false, path = '../io', version = '6.0.0' }
sp-runtime-interface = { default-features = false, path = '../runtime-interface', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[dev-dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }

[features]
default = ['std']
std = [
	'log',
	'sp-core/std',
	'sp-externalities',
	'sp-io/std',
	'sp-runtime-interface/std',
	'sp-std/std',
]
