[package]
name = 'sp-keystore'
version = '0.12.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Keystore primitives.'
documentation = 'https://docs.rs/sp-core'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = '0.1.50'
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
futures = '0.3.21'
merlin = { default-features = false, version = '2.0' }
parking_lot = { default-features = false, version = '0.12.0' }
schnorrkel = { default-features = false, features = ['preaudit_deprecated', 'u64_backend'], version = '0.9.1' }
serde = { optional = true, version = '1.0' }
sp-core = { path = '../core', version = '6.0.0' }
sp-externalities = { default-features = false, path = '../externalities', version = '0.12.0' }
thiserror = '1.0'

[dev-dependencies]
rand = '0.7.2'
rand_chacha = '0.2.2'

[features]
default = ['std']
std = [
	'schnorrkel/std',
	'serde',
]
