[package]
name = 'frame-benchmarking-cli'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'CLI for benchmarking FRAME'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
Inflector = '0.11.4'
chrono = '0.4'
clap = { features = ['derive'], version = '3.1.6' }
codec = { package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { path = '../../../frame/benchmarking', version = '4.0.0-dev' }
frame-support = { path = '../../../frame/support', version = '4.0.0-dev' }
frame-system = { path = '../../../frame/system', version = '4.0.0-dev' }
handlebars = '4.2.2'
hash-db = '0.15.2'
hex = '0.4.3'
itertools = '0.10.3'
kvdb = '0.11.0'
lazy_static = '1.4.0'
linked-hash-map = '0.5.4'
log = '0.4.16'
memory-db = '0.29.0'
prettytable-rs = '0.8.0'
rand = { features = ['small_rng'], version = '0.8.4' }
rand_pcg = '0.3.1'
sc-block-builder = { path = '../../../client/block-builder', version = '0.10.0-dev' }
sc-cli = { path = '../../../client/cli', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-client-db = { path = '../../../client/db', version = '0.10.0-dev' }
sc-executor = { path = '../../../client/executor', version = '0.10.0-dev' }
sc-service = { default-features = false, path = '../../../client/service', version = '0.10.0-dev' }
sc-sysinfo = { path = '../../../client/sysinfo', version = '6.0.0-dev' }
serde = '1.0.136'
serde_json = '1.0.79'
serde_nanos = '0.1.2'
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-database = { path = '../../../primitives/database', version = '4.0.0-dev' }
sp-externalities = { path = '../../../primitives/externalities', version = '0.12.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-keystore = { path = '../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-state-machine = { path = '../../../primitives/state-machine', version = '0.12.0' }
sp-storage = { path = '../../../primitives/storage', version = '6.0.0' }
sp-trie = { path = '../../../primitives/trie', version = '6.0.0' }
tempfile = '3.2.0'
thiserror = '1.0.30'
thousands = '0.2.0'

[features]
default = ['db', 'sc-client-db/runtime-benchmarks']
db = ['sc-client-db/with-kvdb-rocksdb', 'sc-client-db/with-parity-db']
