[package]
name = 'pallet-referenda'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet for inclusive on-chain decisions'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
assert_matches = { optional = true, version = '1.5' }
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0-dev' }

[dev-dependencies]
assert_matches = { version = '1.5' }
pallet-balances = { path = '../balances', version = '4.0.0-dev' }
pallet-preimage = { path = '../preimage', version = '4.0.0-dev' }
pallet-scheduler = { path = '../scheduler', version = '4.0.0-dev' }
sp-core = { path = '../../primitives/core', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'scale-info/std',
	'serde',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
runtime-benchmarks = [
	'assert_matches',
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system/runtime-benchmarks',
	'sp-runtime/runtime-benchmarks',
]
try-runtime = ['frame-support/try-runtime']
