[package]
name = 'sp-authorship'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Authorship primitives'
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = { optional = true, version = '0.1.50' }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
sp-inherents = { default-features = false, path = '../inherents', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[features]
default = [ 'std' ]
std = [
	'async-trait',
	'codec/std',
	'sp-inherents/std',
	'sp-runtime/std',
	'sp-std/std',
]
