[package]
name = 'sp-mmr-primitives'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Merkle Mountain Range primitives.'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
log = { default-features = false, version = '0.4.16' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-api = { default-features = false, path = '../api', version = '4.0.0-dev' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-debug-derive = { default-features = false, path = '../debug-derive', version = '4.0.0' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[dev-dependencies]
hex-literal = '0.3'

[features]
default = ['std']
std = [
	'codec/std',
	'log/std',
	'serde',
	'sp-api/std',
	'sp-core/std',
	'sp-debug-derive/std',
	'sp-runtime/std',
	'sp-std/std',
]
