[package]
name = 'frame-support'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Support code for the runtime.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
bitflags = '1.3'
codec = { default-features = false, features = ['derive', 'max-encoded-len'], package = 'parity-scale-codec', version = '3.0.0' }
frame-metadata = { default-features = false, features = ['v14'], version = '15.0.0' }
frame-support-procedural = { default-features = false, path = './procedural', version = '4.0.0-dev' }
impl-trait-for-tuples = '0.2.2'
k256 = { default-features = false, features = ['ecdsa'], version = '0.10.2' }
log = { default-features = false, version = '0.4.16' }
once_cell = { default-features = false, optional = true, version = '1' }
paste = '1.0'
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
smallvec = '1.8.0'
sp-arithmetic = { default-features = false, path = '../../primitives/arithmetic', version = '5.0.0' }
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-core-hashing-proc-macro = { path = '../../primitives/core/hashing/proc-macro', version = '5.0.0' }
sp-inherents = { default-features = false, path = '../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-staking = { default-features = false, path = '../../primitives/staking', version = '4.0.0-dev' }
sp-state-machine = { optional = true, path = '../../primitives/state-machine', version = '0.12.0' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }
sp-tracing = { default-features = false, path = '../../primitives/tracing', version = '5.0.0' }
tt-call = '1.0.8'

[dev-dependencies]
assert_matches = '1.3.0'
frame-system = { path = '../system', version = '4.0.0-dev' }
parity-util-mem = { default-features = false, features = ['primitive-types'], version = '0.11.0' }
pretty_assertions = '1.0.0'

[features]
default = ['std']
std = [
	'codec/std',
	'frame-metadata/std',
	'frame-support-procedural/std',
	'log/std',
	'once_cell',
	'scale-info/std',
	'serde',
	'sp-arithmetic/std',
	'sp-inherents/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-state-machine',
	'sp-std/std',
	'sp-tracing/std',
]
runtime-benchmarks = []
try-runtime = []
no-metadata-docs = ['frame-support-procedural/no-metadata-docs']
full-metadata-docs = ['scale-info/docs']
