[package]
name = 'sc-consensus-slots'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Generic slots-based utilities for consensus'
edition = '2021'
build = 'build.rs'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = '0.1.50'
codec = { package = 'parity-scale-codec', version = '3.0.0' }
futures = '0.3.21'
futures-timer = '3.0.1'
log = '0.4.16'
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-telemetry = { path = '../../telemetry', version = '4.0.0-dev' }
sp-arithmetic = { path = '../../../primitives/arithmetic', version = '5.0.0' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-slots = { path = '../../../primitives/consensus/slots', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-state-machine = { path = '../../../primitives/state-machine', version = '0.12.0' }
sp-timestamp = { path = '../../../primitives/timestamp', version = '4.0.0-dev' }
thiserror = '1.0.30'

[dev-dependencies]
substrate-test-runtime-client = { path = '../../../test-utils/runtime/client', version = '2.0.0' }
