[package]
description = 'Endpoint to expose Prometheus metrics'
name = 'substrate-prometheus-endpoint'
version = '0.10.0-dev'
license = 'Apache-2.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures-util = { default-features = false, features = ['io'], version = '0.3.19' }
hyper = { default-features = false, features = ['http1', 'server', 'tcp'], version = '0.14.16' }
log = '0.4.16'
prometheus = { default-features = false, version = '0.13.0' }
thiserror = '1.0'
tokio = { features = ['parking_lot'], version = '1.17.0' }

[dev-dependencies]
hyper = { features = ['client'], version = '0.14.16' }
tokio = { features = ['rt-multi-thread'], version = '1.17.0' }
