[package]
name = 'sp-runtime'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Runtime Modules shared primitive types.'
documentation = 'https://docs.rs/sp-runtime'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive', 'max-encoded-len'], package = 'parity-scale-codec', version = '3.0.0' }
either = { default-features = false, version = '1.5' }
hash256-std-hasher = { default-features = false, version = '0.15.2' }
impl-trait-for-tuples = '0.2.2'
log = { default-features = false, version = '0.4.16' }
parity-util-mem = { default-features = false, features = ['primitive-types'], version = '0.11.0' }
paste = '1.0'
rand = { optional = true, version = '0.7.2' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-application-crypto = { default-features = false, path = '../application-crypto', version = '6.0.0' }
sp-arithmetic = { default-features = false, path = '../arithmetic', version = '5.0.0' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-io = { default-features = false, path = '../io', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[dev-dependencies]
rand = '0.7.2'
serde_json = '1.0.79'
sp-api = { path = '../api', version = '4.0.0-dev' }
sp-state-machine = { path = '../state-machine', version = '0.12.0' }
sp-tracing = { path = '../../primitives/tracing', version = '5.0.0' }
substrate-test-runtime-client = { path = '../../test-utils/runtime/client', version = '2.0.0' }
zstd = { default-features = false, version = '0.10.0' }

[features]
bench = []
runtime-benchmarks = []
default = ['std']
std = [
	'codec/std',
	'either/use_std',
	'hash256-std-hasher/std',
	'log/std',
	'parity-util-mem/std',
	'rand',
	'scale-info/std',
	'serde',
	'sp-application-crypto/std',
	'sp-arithmetic/std',
	'sp-core/std',
	'sp-io/std',
	'sp-std/std',
]
