[package]
name = 'node-runtime'
version = '3.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
build = 'build.rs'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = [
	'derive',
	'max-encoded-len',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../../../frame/benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '../../../frame/election-provider-support', version = '4.0.0-dev' }
frame-executive = { default-features = false, path = '../../../frame/executive', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../../../frame/support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../../frame/system', version = '4.0.0-dev' }
frame-system-benchmarking = { default-features = false, optional = true, path = '../../../frame/system/benchmarking', version = '4.0.0-dev' }
frame-system-rpc-runtime-api = { default-features = false, path = '../../../frame/system/rpc/runtime-api/', version = '4.0.0-dev' }
frame-try-runtime = { default-features = false, optional = true, path = '../../../frame/try-runtime', version = '0.10.0-dev' }
hex-literal = { optional = true, version = '0.3.4' }
log = { default-features = false, version = '0.4.16' }
node-primitives = { default-features = false, path = '../primitives', version = '2.0.0' }
pallet-asset-tx-payment = { default-features = false, path = '../../../frame/transaction-payment/asset-tx-payment/', version = '4.0.0-dev' }
pallet-assets = { default-features = false, path = '../../../frame/assets', version = '4.0.0-dev' }
pallet-authority-discovery = { default-features = false, path = '../../../frame/authority-discovery', version = '4.0.0-dev' }
pallet-authorship = { default-features = false, path = '../../../frame/authorship', version = '4.0.0-dev' }
pallet-babe = { default-features = false, path = '../../../frame/babe', version = '4.0.0-dev' }
pallet-bags-list = { default-features = false, path = '../../../frame/bags-list', version = '4.0.0-dev' }
pallet-balances = { default-features = false, path = '../../../frame/balances', version = '4.0.0-dev' }
pallet-bounties = { default-features = false, path = '../../../frame/bounties', version = '4.0.0-dev' }
pallet-child-bounties = { default-features = false, path = '../../../frame/child-bounties', version = '4.0.0-dev' }
pallet-collective = { default-features = false, path = '../../../frame/collective', version = '4.0.0-dev' }
pallet-contracts = { default-features = false, path = '../../../frame/contracts', version = '4.0.0-dev' }
pallet-contracts-primitives = { default-features = false, path = '../../../frame/contracts/common/', version = '6.0.0' }
pallet-contracts-rpc-runtime-api = { default-features = false, path = '../../../frame/contracts/rpc/runtime-api/', version = '4.0.0-dev' }
pallet-conviction-voting = { default-features = false, path = '../../../frame/conviction-voting', version = '4.0.0-dev' }
pallet-democracy = { default-features = false, path = '../../../frame/democracy', version = '4.0.0-dev' }
pallet-election-provider-multi-phase = { default-features = false, path = '../../../frame/election-provider-multi-phase', version = '4.0.0-dev' }
pallet-election-provider-support-benchmarking = { default-features = false, optional = true, path = '../../../frame/election-provider-support/benchmarking', version = '4.0.0-dev' }
pallet-elections-phragmen = { default-features = false, path = '../../../frame/elections-phragmen', version = '5.0.0-dev' }
pallet-gilt = { default-features = false, path = '../../../frame/gilt', version = '4.0.0-dev' }
pallet-grandpa = { default-features = false, path = '../../../frame/grandpa', version = '4.0.0-dev' }
pallet-identity = { default-features = false, path = '../../../frame/identity', version = '4.0.0-dev' }
pallet-im-online = { default-features = false, path = '../../../frame/im-online', version = '4.0.0-dev' }
pallet-indices = { default-features = false, path = '../../../frame/indices', version = '4.0.0-dev' }
pallet-lottery = { default-features = false, path = '../../../frame/lottery', version = '4.0.0-dev' }
pallet-membership = { default-features = false, path = '../../../frame/membership', version = '4.0.0-dev' }
pallet-mmr = { default-features = false, path = '../../../frame/merkle-mountain-range', version = '4.0.0-dev' }
pallet-multisig = { default-features = false, path = '../../../frame/multisig', version = '4.0.0-dev' }
pallet-nomination-pools = { default-features = false, path = '../../../frame/nomination-pools', version = '1.0.0' }
pallet-nomination-pools-benchmarking = { default-features = false, optional = true, path = '../../../frame/nomination-pools/benchmarking', version = '1.0.0' }
pallet-offences = { default-features = false, path = '../../../frame/offences', version = '4.0.0-dev' }
pallet-offences-benchmarking = { default-features = false, optional = true, path = '../../../frame/offences/benchmarking', version = '4.0.0-dev' }
pallet-preimage = { default-features = false, path = '../../../frame/preimage', version = '4.0.0-dev' }
pallet-proxy = { default-features = false, path = '../../../frame/proxy', version = '4.0.0-dev' }
pallet-randomness-collective-flip = { default-features = false, path = '../../../frame/randomness-collective-flip', version = '4.0.0-dev' }
pallet-recovery = { default-features = false, path = '../../../frame/recovery', version = '4.0.0-dev' }
pallet-referenda = { default-features = false, path = '../../../frame/referenda', version = '4.0.0-dev' }
pallet-remark = { default-features = false, path = '../../../frame/remark', version = '4.0.0-dev' }
pallet-scheduler = { default-features = false, path = '../../../frame/scheduler', version = '4.0.0-dev' }
pallet-session = { default-features = false, features = [ 'historical' ], path = '../../../frame/session', version = '4.0.0-dev' }
pallet-session-benchmarking = { default-features = false, optional = true, path = '../../../frame/session/benchmarking', version = '4.0.0-dev' }
pallet-society = { default-features = false, path = '../../../frame/society', version = '4.0.0-dev' }
pallet-staking = { default-features = false, path = '../../../frame/staking', version = '4.0.0-dev' }
pallet-staking-reward-curve = { default-features = false, path = '../../../frame/staking/reward-curve', version = '4.0.0-dev' }
pallet-state-trie-migration = { default-features = false, path = '../../../frame/state-trie-migration', version = '4.0.0-dev' }
pallet-sudo = { default-features = false, path = '../../../frame/sudo', version = '4.0.0-dev' }
pallet-timestamp = { default-features = false, path = '../../../frame/timestamp', version = '4.0.0-dev' }
pallet-tips = { default-features = false, path = '../../../frame/tips', version = '4.0.0-dev' }
pallet-transaction-payment = { default-features = false, path = '../../../frame/transaction-payment', version = '4.0.0-dev' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, path = '../../../frame/transaction-payment/rpc/runtime-api/', version = '4.0.0-dev' }
pallet-transaction-storage = { default-features = false, path = '../../../frame/transaction-storage', version = '4.0.0-dev' }
pallet-treasury = { default-features = false, path = '../../../frame/treasury', version = '4.0.0-dev' }
pallet-uniques = { default-features = false, path = '../../../frame/uniques', version = '4.0.0-dev' }
pallet-utility = { default-features = false, path = '../../../frame/utility', version = '4.0.0-dev' }
pallet-vesting = { default-features = false, path = '../../../frame/vesting', version = '4.0.0-dev' }
pallet-whitelist = { default-features = false, path = '../../../frame/whitelist', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-api = { default-features = false, path = '../../../primitives/api', version = '4.0.0-dev' }
sp-authority-discovery = { default-features = false, path = '../../../primitives/authority-discovery', version = '4.0.0-dev' }
sp-block-builder = { default-features = false, path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-consensus-babe = { default-features = false, path = '../../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { default-features = false, path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { default-features = false, path = '../../../primitives/io', version = '6.0.0' }
sp-offchain = { default-features = false, path = '../../../primitives/offchain', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-sandbox = { default-features = false, path = '../../../primitives/sandbox', version = '0.10.0-dev' }
sp-session = { default-features = false, path = '../../../primitives/session', version = '4.0.0-dev' }
sp-staking = { default-features = false, path = '../../../primitives/staking', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }
sp-transaction-pool = { default-features = false, path = '../../../primitives/transaction-pool', version = '4.0.0-dev' }
sp-version = { default-features = false, path = '../../../primitives/version', version = '5.0.0' }
static_assertions = '1.1.0'

[build-dependencies]
substrate-wasm-builder = { version = '5.0.0-dev', path = '../../../utils/wasm-builder' }

[features]
default = ['std']
with-tracing = ['frame-executive/with-tracing']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-executive/std',
	'frame-support/std',
	'frame-system-rpc-runtime-api/std',
	'frame-system/std',
	'frame-try-runtime/std',
	'log/std',
	'node-primitives/std',
	'pallet-assets/std',
	'pallet-authority-discovery/std',
	'pallet-authorship/std',
	'pallet-babe/std',
	'pallet-bags-list/std',
	'pallet-balances/std',
	'pallet-bounties/std',
	'pallet-child-bounties/std',
	'pallet-collective/std',
	'pallet-contracts-primitives/std',
	'pallet-contracts-rpc-runtime-api/std',
	'pallet-contracts/std',
	'pallet-conviction-voting/std',
	'pallet-democracy/std',
	'pallet-election-provider-multi-phase/std',
	'pallet-elections-phragmen/std',
	'pallet-gilt/std',
	'pallet-grandpa/std',
	'pallet-identity/std',
	'pallet-im-online/std',
	'pallet-indices/std',
	'pallet-lottery/std',
	'pallet-membership/std',
	'pallet-mmr/std',
	'pallet-multisig/std',
	'pallet-nomination-pools/std',
	'pallet-offences/std',
	'pallet-preimage/std',
	'pallet-proxy/std',
	'pallet-randomness-collective-flip/std',
	'pallet-recovery/std',
	'pallet-referenda/std',
	'pallet-remark/std',
	'pallet-scheduler/std',
	'pallet-session/std',
	'pallet-society/std',
	'pallet-staking/std',
	'pallet-state-trie-migration/std',
	'pallet-sudo/std',
	'pallet-timestamp/std',
	'pallet-tips/std',
	'pallet-transaction-payment-rpc-runtime-api/std',
	'pallet-transaction-payment/std',
	'pallet-transaction-storage/std',
	'pallet-treasury/std',
	'pallet-uniques/std',
	'pallet-utility/std',
	'pallet-vesting/std',
	'scale-info/std',
	'sp-api/std',
	'sp-authority-discovery/std',
	'sp-block-builder/std',
	'sp-consensus-babe/std',
	'sp-core/std',
	'sp-inherents/std',
	'sp-io/std',
	'sp-offchain/std',
	'sp-runtime/std',
	'sp-session/std',
	'sp-staking/std',
	'sp-std/std',
	'sp-transaction-pool/std',
	'sp-version/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'hex-literal',
	'pallet-assets/runtime-benchmarks',
	'pallet-babe/runtime-benchmarks',
	'pallet-bags-list/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-bounties/runtime-benchmarks',
	'pallet-child-bounties/runtime-benchmarks',
	'pallet-collective/runtime-benchmarks',
	'pallet-contracts/runtime-benchmarks',
	'pallet-conviction-voting/runtime-benchmarks',
	'pallet-democracy/runtime-benchmarks',
	'pallet-election-provider-multi-phase/runtime-benchmarks',
	'pallet-election-provider-support-benchmarking/runtime-benchmarks',
	'pallet-elections-phragmen/runtime-benchmarks',
	'pallet-gilt/runtime-benchmarks',
	'pallet-grandpa/runtime-benchmarks',
	'pallet-identity/runtime-benchmarks',
	'pallet-im-online/runtime-benchmarks',
	'pallet-indices/runtime-benchmarks',
	'pallet-lottery/runtime-benchmarks',
	'pallet-membership/runtime-benchmarks',
	'pallet-mmr/runtime-benchmarks',
	'pallet-multisig/runtime-benchmarks',
	'pallet-nomination-pools-benchmarking',
	'pallet-offences-benchmarking',
	'pallet-preimage/runtime-benchmarks',
	'pallet-proxy/runtime-benchmarks',
	'pallet-recovery/runtime-benchmarks',
	'pallet-referenda/runtime-benchmarks',
	'pallet-remark/runtime-benchmarks',
	'pallet-scheduler/runtime-benchmarks',
	'pallet-session-benchmarking',
	'pallet-society/runtime-benchmarks',
	'pallet-staking/runtime-benchmarks',
	'pallet-state-trie-migration/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'pallet-tips/runtime-benchmarks',
	'pallet-transaction-storage/runtime-benchmarks',
	'pallet-treasury/runtime-benchmarks',
	'pallet-uniques/runtime-benchmarks',
	'pallet-utility/runtime-benchmarks',
	'pallet-vesting/runtime-benchmarks',
	'pallet-whitelist/runtime-benchmarks',
	'sp-runtime/runtime-benchmarks',
]
try-runtime = [
	'frame-executive/try-runtime',
	'frame-system/try-runtime',
	'frame-try-runtime',
	'pallet-assets/try-runtime',
	'pallet-authority-discovery/try-runtime',
	'pallet-authorship/try-runtime',
	'pallet-babe/try-runtime',
	'pallet-balances/try-runtime',
	'pallet-bounties/try-runtime',
	'pallet-child-bounties/try-runtime',
	'pallet-collective/try-runtime',
	'pallet-contracts/try-runtime',
	'pallet-conviction-voting/try-runtime',
	'pallet-democracy/try-runtime',
	'pallet-election-provider-multi-phase/try-runtime',
	'pallet-elections-phragmen/try-runtime',
	'pallet-gilt/try-runtime',
	'pallet-grandpa/try-runtime',
	'pallet-identity/try-runtime',
	'pallet-im-online/try-runtime',
	'pallet-indices/try-runtime',
	'pallet-lottery/try-runtime',
	'pallet-membership/try-runtime',
	'pallet-mmr/try-runtime',
	'pallet-multisig/try-runtime',
	'pallet-offences/try-runtime',
	'pallet-preimage/try-runtime',
	'pallet-proxy/try-runtime',
	'pallet-randomness-collective-flip/try-runtime',
	'pallet-recovery/try-runtime',
	'pallet-referenda/try-runtime',
	'pallet-scheduler/try-runtime',
	'pallet-session/try-runtime',
	'pallet-society/try-runtime',
	'pallet-staking/try-runtime',
	'pallet-state-trie-migration/try-runtime',
	'pallet-sudo/try-runtime',
	'pallet-timestamp/try-runtime',
	'pallet-tips/try-runtime',
	'pallet-transaction-payment/try-runtime',
	'pallet-treasury/try-runtime',
	'pallet-uniques/try-runtime',
	'pallet-utility/try-runtime',
	'pallet-vesting/try-runtime',
	'pallet-whitelist/try-runtime',
]
contracts-unstable-interface = ['pallet-contracts/unstable-interface']
wasmer-sandbox = ['sp-sandbox/wasmer-sandbox']
