targets = [
]

[advisories]
db-path = '~/.cargo/advisory-db'
db-url = 'https://github.com/rustsec/advisory-db'
vulnerability = 'deny'
unmaintained = 'warn'
yanked = 'warn'
notice = 'warn'
ignore = [
]

[licenses]
unlicensed = 'deny'
allow = [
]
deny = [
]
copyleft = 'allow'
allow-osi-fsf-free = 'either'
default = 'deny'
confidence-threshold = 0.9
exceptions = [
]

[[licenses.clarify]]
name = 'ring'
expression = 'OpenSSL'
license-files = [
	{ path = 'LICENSE', hash = 3171872035 },
]

[[licenses.clarify]]
name = 'webpki'
expression = 'ISC'
license-files = [{ path = 'LICENSE', hash = 1867372 }]

[licenses.private]
ignore = false
registries = [
]

[bans]
multiple-versions = 'warn'
highlight = 'lowest-version'
allow = [
]
deny = [
	{ name = 'parity-util-mem', version = '<0.6' },
]
skip = [
]
skip-tree = [
]

[sources]
unknown-registry = 'deny'
unknown-git = 'warn'
allow-registry = ['https://github.com/rust-lang/crates.io-index']
allow-git = []
