[package]
name = 'pallet-bags-list-remote-tests'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet bags list remote test'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
frame-election-provider-support = { path = '../../election-provider-support', version = '4.0.0-dev' }
frame-support = { path = '../../support', version = '4.0.0-dev' }
frame-system = { path = '../../system', version = '4.0.0-dev' }
log = '0.4.16'
pallet-bags-list = { path = '../../bags-list', version = '4.0.0-dev' }
pallet-staking = { path = '../../staking', version = '4.0.0-dev' }
remote-externalities = { path = '../../../utils/frame/remote-externalities', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-std = { path = '../../../primitives/std', version = '4.0.0' }
sp-storage = { path = '../../../primitives/storage', version = '6.0.0' }
sp-tracing = { path = '../../../primitives/tracing', version = '5.0.0' }
tokio = { features = ['macros'], version = '1' }
