[package]
name = 'pallet-offences-benchmarking'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME offences pallet benchmarking'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, path = '../../benchmarking', version = '4.0.0-dev' }
frame-election-provider-support = { default-features = false, path = '../../election-provider-support', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../system', version = '4.0.0-dev' }
pallet-babe = { default-features = false, path = '../../babe', version = '4.0.0-dev' }
pallet-balances = { default-features = false, path = '../../balances', version = '4.0.0-dev' }
pallet-grandpa = { default-features = false, path = '../../grandpa', version = '4.0.0-dev' }
pallet-im-online = { default-features = false, path = '../../im-online', version = '4.0.0-dev' }
pallet-offences = { default-features = false, features = [
	'runtime-benchmarks',
], path = '../../offences', version = '4.0.0-dev' }
pallet-session = { default-features = false, path = '../../session', version = '4.0.0-dev' }
pallet-staking = { default-features = false, features = [
	'runtime-benchmarks',
], path = '../../staking', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.0' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-staking = { default-features = false, path = '../../../primitives/staking', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }

[dev-dependencies]
pallet-staking-reward-curve = { path = '../../staking/reward-curve', version = '4.0.0-dev' }
pallet-timestamp = { path = '../../timestamp', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-election-provider-support/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-babe/std',
	'pallet-balances/std',
	'pallet-grandpa/std',
	'pallet-im-online/std',
	'pallet-offences/std',
	'pallet-session/std',
	'pallet-staking/std',
	'scale-info/std',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
