[package]
name = 'pallet-bags-list-fuzzer'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Fuzzer for FRAME pallet bags list'
readme = 'README.md'
publish = false

[dependencies]
frame-election-provider-support = { features = ['runtime-benchmarks'], path = '../../election-provider-support', version = '4.0.0-dev' }
honggfuzz = '0.5'
pallet-bags-list = { features = ['fuzz'], path = '..', version = '4.0.0-dev' }
rand = { features = ['std', 'small_rng'], version = '0.8' }

[[bin]]
name = 'bags-list'
path = 'src/main.rs'
