[package]
name = 'node-rpc'
version = '3.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
jsonrpc-core = '18.0.0'
node-primitives = { path = '../primitives', version = '2.0.0' }
pallet-contracts-rpc = { path = '../../../frame/contracts/rpc/', version = '4.0.0-dev' }
pallet-mmr-rpc = { path = '../../../frame/merkle-mountain-range/rpc/', version = '3.0.0' }
pallet-transaction-payment-rpc = { path = '../../../frame/transaction-payment/rpc/', version = '4.0.0-dev' }
sc-chain-spec = { path = '../../../client/chain-spec', version = '4.0.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-consensus-babe = { path = '../../../client/consensus/babe', version = '0.10.0-dev' }
sc-consensus-babe-rpc = { path = '../../../client/consensus/babe/rpc', version = '0.10.0-dev' }
sc-consensus-epochs = { path = '../../../client/consensus/epochs', version = '0.10.0-dev' }
sc-finality-grandpa = { path = '../../../client/finality-grandpa', version = '0.10.0-dev' }
sc-finality-grandpa-rpc = { path = '../../../client/finality-grandpa/rpc', version = '0.10.0-dev' }
sc-rpc = { path = '../../../client/rpc', version = '4.0.0-dev' }
sc-rpc-api = { path = '../../../client/rpc-api', version = '0.10.0-dev' }
sc-sync-state-rpc = { path = '../../../client/sync-state-rpc', version = '0.10.0-dev' }
sc-transaction-pool-api = { path = '../../../client/transaction-pool/api', version = '4.0.0-dev' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-block-builder = { path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-babe = { path = '../../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-keystore = { path = '../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
substrate-frame-rpc-system = { path = '../../../utils/frame/rpc/system', version = '4.0.0-dev' }
substrate-state-trie-migration-rpc = { path = '../../../utils/frame/rpc/state-trie-migration-rpc/', version = '4.0.0-dev' }
