[package]
name = 'sp-timestamp'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Substrate core types and inherents for timestamps.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = { optional = true, version = '0.1.50' }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
futures-timer = { optional = true, version = '3.0.2' }
log = { optional = true, version = '0.4.16' }
sp-api = { default-features = false, path = '../api', version = '4.0.0-dev' }
sp-inherents = { default-features = false, path = '../inherents', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
thiserror = { optional = true, version = '1.0.30' }

[features]
default = [ 'std' ]
std = [
	'async-trait',
	'codec/std',
	'futures-timer',
	'log',
	'sp-api/std',
	'sp-inherents/std',
	'sp-runtime/std',
	'sp-std/std',
	'thiserror',
]
