[package]
name = 'sp-consensus-aura'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Primitives for Aura consensus'
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = { optional = true, version = '0.1.50' }
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-api = { default-features = false, path = '../../api', version = '4.0.0-dev' }
sp-application-crypto = { default-features = false, path = '../../application-crypto', version = '6.0.0' }
sp-consensus = { optional = true, path = '../common', version = '0.10.0-dev' }
sp-consensus-slots = { default-features = false, path = '../slots', version = '0.10.0-dev' }
sp-inherents = { default-features = false, path = '../../inherents', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../std', version = '4.0.0' }
sp-timestamp = { default-features = false, path = '../../timestamp', version = '4.0.0-dev' }

[features]
default = ['std']
std = [
	'async-trait',
	'codec/std',
	'scale-info/std',
	'sp-api/std',
	'sp-application-crypto/std',
	'sp-consensus',
	'sp-consensus-slots/std',
	'sp-inherents/std',
	'sp-runtime/std',
	'sp-std/std',
	'sp-timestamp/std',
]
