[package]
name = 'pallet-transaction-storage'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Unlicense'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Storage chain pallet'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
hex-literal = { optional = true, version = '0.3.4' }
pallet-balances = { default-features = false, path = '../balances', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { optional = true, version = '1.0.136' }
sp-inherents = { default-features = false, path = '../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }
sp-transaction-storage-proof = { default-features = false, path = '../../primitives/transaction-storage-proof', version = '4.0.0-dev' }

[dev-dependencies]
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-transaction-storage-proof = { default-features = true, path = '../../primitives/transaction-storage-proof', version = '4.0.0-dev' }

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking/runtime-benchmarks', 'hex-literal']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-balances/std',
	'scale-info/std',
	'serde',
	'sp-inherents/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
