[package]
name = 'sc-consensus-babe-rpc'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'RPC extensions for the BABE consensus algorithm'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = '0.3.21'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
sc-consensus-babe = { path = '../', version = '0.10.0-dev' }
sc-consensus-epochs = { path = '../../epochs', version = '0.10.0-dev' }
sc-rpc-api = { path = '../../../rpc-api', version = '0.10.0-dev' }
serde = { features = ['derive'], version = '1.0.136' }
sp-api = { path = '../../../../primitives/api', version = '4.0.0-dev' }
sp-application-crypto = { path = '../../../../primitives/application-crypto', version = '6.0.0' }
sp-blockchain = { path = '../../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-babe = { path = '../../../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-core = { path = '../../../../primitives/core', version = '6.0.0' }
sp-keystore = { path = '../../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../../primitives/runtime', version = '6.0.0' }
thiserror = '1.0'

[dev-dependencies]
sc-consensus = { path = '../../../consensus/common', version = '0.10.0-dev' }
sc-keystore = { path = '../../../keystore', version = '4.0.0-dev' }
serde_json = '1.0.79'
sp-keyring = { path = '../../../../primitives/keyring', version = '6.0.0' }
substrate-test-runtime-client = { path = '../../../../test-utils/runtime/client', version = '2.0.0' }
tempfile = '3.1.0'
