[package]
name = 'pallet-contracts-primitives'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'A crate that hosts a common definitions that are relevant for the pallet-contracts.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
bitflags = '1.0'
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.0' }
serde = { features = ['derive'], optional = true, version = '1' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-rpc = { optional = true, path = '../../../primitives/rpc', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'serde',
	'sp-core/std',
	'sp-rpc',
	'sp-runtime/std',
	'sp-std/std',
]
