[package]
name = 'substrate-test-runtime-client'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
futures = '0.3.21'
sc-block-builder = { path = '../../../client/block-builder', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
substrate-test-client = { path = '../../client', version = '2.0.0' }
substrate-test-runtime = { path = '../../runtime', version = '2.0.0' }
