[package]
name = 'pallet-example-offchain-worker'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Unlicense'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME example pallet for offchain worker'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
frame-support = { default-features = false, path = '../../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../system', version = '4.0.0-dev' }
lite-json = { default-features = false, version = '0.1' }
log = { default-features = false, version = '0.4.16' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-io = { default-features = false, path = '../../../primitives/io', version = '6.0.0' }
sp-keystore = { optional = true, path = '../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'lite-json/std',
	'log/std',
	'scale-info/std',
	'sp-core/std',
	'sp-io/std',
	'sp-keystore',
	'sp-runtime/std',
	'sp-std/std',
]
try-runtime = ['frame-support/try-runtime']
