[package]
name = 'sp-core'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Shareable Substrate types.'
documentation = 'https://docs.rs/sp-core'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
base58 = { version = '0.2.0', optional = true }
bitflags = '1.3'
blake2-rfc = { version = '0.2.18', default-features = false, optional = true }
byteorder = { version = '1.3.2', default-features = false }
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = [
	'derive',
	'max-encoded-len',
] }
dyn-clonable = { version = '0.9.0', optional = true }
ed25519-dalek = { version = '1.0.1', default-features = false, features = ['u64_backend', 'alloc'], optional = true }
futures = { version = '0.3.21', optional = true }
hash-db = { version = '0.15.2', default-features = false }
hash256-std-hasher = { version = '0.15.2', default-features = false }
hex = { version = '0.4', default-features = false, optional = true }
impl-serde = { version = '0.3.0', optional = true }
lazy_static = { version = '1.4.0', default-features = false, optional = true }
libsecp256k1 = { version = '0.7', default-features = false, features = ['static-context'], optional = true }
log = { version = '0.4.16', default-features = false }
merlin = { version = '2.0', default-features = false, optional = true }
num-traits = { version = '0.2.8', default-features = false }
parity-util-mem = { version = '0.11.0', default-features = false, features = ['primitive-types'] }
parking_lot = { version = '0.12.0', optional = true }
primitive-types = { version = '0.11.1', default-features = false, features = ['codec', 'scale-info'] }
rand = { version = '0.7.3', optional = true, features = ['small_rng'] }
regex = { version = '1.5.4', optional = true }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
schnorrkel = { version = '0.9.1', features = [
	'preaudit_deprecated',
	'u64_backend',
], default-features = false, optional = true }
secp256k1 = { version = '0.21.2', default-features = false, features = ['recovery', 'alloc'], optional = true }
secrecy = { version = '0.8.0', default-features = false }
serde = { version = '1.0.136', optional = true, features = ['derive'] }
sp-core-hashing = { version = '4.0.0', path = './hashing', default-features = false, optional = true }
sp-debug-derive = { version = '4.0.0', default-features = false, path = '../debug-derive' }
sp-externalities = { version = '0.12.0', optional = true, path = '../externalities' }
sp-runtime-interface = { version = '6.0.0', default-features = false, path = '../runtime-interface' }
sp-std = { version = '4.0.0', default-features = false, path = '../std' }
sp-storage = { version = '6.0.0', default-features = false, path = '../storage' }
ss58-registry = { version = '1.17.0', default-features = false }
substrate-bip39 = { version = '0.4.4', optional = true }
thiserror = { version = '1.0.30', optional = true }
tiny-bip39 = { version = '0.8.2', optional = true }
wasmi = { version = '0.9.1', optional = true }
zeroize = { version = '1.4.3', default-features = false }

[dev-dependencies]
criterion = '0.3.3'
hex-literal = '0.3.4'
rand = '0.7.2'
serde_json = '1.0'
sp-core-hashing-proc-macro = { version = '5.0.0', path = './hashing/proc-macro' }
sp-serializer = { version = '4.0.0-dev', path = '../serializer' }

[[bench]]
name = 'bench'
harness = false

[lib]
bench = false

[features]
default = ['std']
std = [
	'base58',
	'blake2-rfc/std',
	'byteorder/std',
	'codec/std',
	'dyn-clonable',
	'ed25519-dalek/std',
	'full_crypto',
	'futures',
	'futures/thread-pool',
	'hash-db/std',
	'hash256-std-hasher/std',
	'hex/std',
	'impl-serde',
	'lazy_static',
	'libsecp256k1/std',
	'log/std',
	'num-traits/std',
	'parking_lot',
	'primitive-types/byteorder',
	'primitive-types/rustc-hex',
	'primitive-types/serde',
	'primitive-types/std',
	'rand',
	'regex',
	'scale-info/std',
	'schnorrkel/std',
	'secp256k1/global-context',
	'secp256k1/std',
	'secrecy/alloc',
	'serde',
	'sp-core-hashing/std',
	'sp-debug-derive/std',
	'sp-externalities',
	'sp-runtime-interface/std',
	'sp-std/std',
	'sp-storage/std',
	'ss58-registry/std',
	'substrate-bip39',
	'thiserror',
	'tiny-bip39',
	'wasmi',
	'zeroize/alloc',
]
full_crypto = [
	'blake2-rfc',
	'ed25519-dalek',
	'hex',
	'libsecp256k1',
	'merlin',
	'schnorrkel',
	'secp256k1',
	'sp-core-hashing',
	'sp-runtime-interface/disable_target_static_assertions',
]
