[package]
name = 'sp-core'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Shareable Substrate types.'
documentation = 'https://docs.rs/sp-core'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
base58 = { optional = true, version = '0.2.0' }
bitflags = '1.3'
blake2-rfc = { default-features = false, optional = true, version = '0.2.18' }
byteorder = { default-features = false, version = '1.3.2' }
codec = { default-features = false, features = [
	'derive',
	'max-encoded-len',
], package = 'parity-scale-codec', version = '3.0.0' }
dyn-clonable = { optional = true, version = '0.9.0' }
ed25519-dalek = { default-features = false, features = ['u64_backend', 'alloc'], optional = true, version = '1.0.1' }
futures = { optional = true, version = '0.3.21' }
hash-db = { default-features = false, version = '0.15.2' }
hash256-std-hasher = { default-features = false, version = '0.15.2' }
hex = { default-features = false, optional = true, version = '0.4' }
impl-serde = { optional = true, version = '0.3.0' }
lazy_static = { default-features = false, optional = true, version = '1.4.0' }
libsecp256k1 = { default-features = false, features = ['static-context'], optional = true, version = '0.7' }
log = { default-features = false, version = '0.4.16' }
merlin = { default-features = false, optional = true, version = '2.0' }
num-traits = { default-features = false, version = '0.2.8' }
parity-util-mem = { default-features = false, features = ['primitive-types'], version = '0.11.0' }
parking_lot = { optional = true, version = '0.12.0' }
primitive-types = { default-features = false, features = ['codec', 'scale-info'], version = '0.11.1' }
rand = { features = ['small_rng'], optional = true, version = '0.7.3' }
regex = { optional = true, version = '1.5.4' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
schnorrkel = { default-features = false, features = [
	'preaudit_deprecated',
	'u64_backend',
], optional = true, version = '0.9.1' }
secp256k1 = { default-features = false, features = ['recovery', 'alloc'], optional = true, version = '0.21.2' }
secrecy = { default-features = false, version = '0.8.0' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-core-hashing = { default-features = false, optional = true, path = './hashing', version = '4.0.0' }
sp-debug-derive = { default-features = false, path = '../debug-derive', version = '4.0.0' }
sp-externalities = { optional = true, path = '../externalities', version = '0.12.0' }
sp-runtime-interface = { default-features = false, path = '../runtime-interface', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-storage = { default-features = false, path = '../storage', version = '6.0.0' }
ss58-registry = { default-features = false, version = '1.17.0' }
substrate-bip39 = { optional = true, version = '0.4.4' }
thiserror = { optional = true, version = '1.0.30' }
tiny-bip39 = { optional = true, version = '0.8.2' }
wasmi = { optional = true, version = '0.9.1' }
zeroize = { default-features = false, version = '1.4.3' }

[dev-dependencies]
criterion = '0.3.3'
hex-literal = '0.3.4'
rand = '0.7.2'
serde_json = '1.0'
sp-core-hashing-proc-macro = { path = './hashing/proc-macro', version = '5.0.0' }
sp-serializer = { path = '../serializer', version = '4.0.0-dev' }

[[bench]]
name = 'bench'
harness = false

[lib]
bench = false

[features]
default = ['std']
std = [
	'base58',
	'blake2-rfc/std',
	'byteorder/std',
	'codec/std',
	'dyn-clonable',
	'ed25519-dalek/std',
	'full_crypto',
	'futures',
	'futures/thread-pool',
	'hash-db/std',
	'hash256-std-hasher/std',
	'hex/std',
	'impl-serde',
	'lazy_static',
	'libsecp256k1/std',
	'log/std',
	'num-traits/std',
	'parking_lot',
	'primitive-types/byteorder',
	'primitive-types/rustc-hex',
	'primitive-types/serde',
	'primitive-types/std',
	'rand',
	'regex',
	'scale-info/std',
	'schnorrkel/std',
	'secp256k1/global-context',
	'secp256k1/std',
	'secrecy/alloc',
	'serde',
	'sp-core-hashing/std',
	'sp-debug-derive/std',
	'sp-externalities',
	'sp-runtime-interface/std',
	'sp-std/std',
	'sp-storage/std',
	'ss58-registry/std',
	'substrate-bip39',
	'thiserror',
	'tiny-bip39',
	'wasmi',
	'zeroize/alloc',
]
full_crypto = [
	'blake2-rfc',
	'ed25519-dalek',
	'hex',
	'libsecp256k1',
	'merlin',
	'schnorrkel',
	'secp256k1',
	'sp-core-hashing',
	'sp-runtime-interface/disable_target_static_assertions',
]
