[package]
name = 'sp-inherents'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Provides types and traits for creating and checking inherents.'
documentation = 'https://docs.rs/sp-inherents'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = { optional = true, version = '0.1.50' }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
impl-trait-for-tuples = '0.2.2'
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-runtime = { optional = true, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
thiserror = { optional = true, version = '1.0.30' }

[dev-dependencies]
futures = '0.3.21'

[features]
default = [ 'std' ]
std = [
	'async-trait',
	'codec/std',
	'sp-core/std',
	'sp-runtime',
	'sp-std/std',
	'thiserror',
]
