[package]
name = 'sp-consensus-vrf'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Primitives for VRF based consensus'
edition = '2021'
license = 'Apache-2.0'
repository = 'https://github.com/paritytech/substrate/'
homepage = 'https://substrate.io'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
schnorrkel = { default-features = false, features = ['preaudit_deprecated', 'u64_backend'], version = '0.9.1' }
sp-core = { default-features = false, path = '../../core', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../../std', version = '4.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'schnorrkel/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-std/std',
]
