[package]
name = 'sp-application-crypto'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
description = 'Provides facilities for generating application specific crypto wrapper types.'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
documentation = 'https://docs.rs/sp-application-crypto'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, features = ['derive'] }
scale-info = { version = '2.0.1', default-features = false, features = ['derive'] }
serde = { version = '1.0.136', optional = true, features = ['derive'] }
sp-core = { version = '6.0.0', default-features = false, path = '../core' }
sp-io = { version = '6.0.0', default-features = false, path = '../io' }
sp-std = { version = '4.0.0', default-features = false, path = '../std' }

[features]
default = [ 'std' ]
std = [
	'codec/std',
	'full_crypto',
	'scale-info/std',
	'serde',
	'sp-core/std',
	'sp-io/std',
	'sp-std/std',
]
full_crypto = [
	'sp-core/full_crypto',
	'sp-io/disable_oom',
	'sp-io/disable_panic_handler',
]
