[package]
name = 'sc-consensus'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Collection of common consensus specific imlementations for Substrate (client)'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = '0.1.42'
futures = { features = ['thread-pool'], version = '0.3.21' }
futures-timer = '3.0.1'
libp2p = { default-features = false, version = '0.44.0' }
log = '0.4.16'
parking_lot = '0.12.0'
prometheus-endpoint = { package = 'substrate-prometheus-endpoint', path = '../../../utils/prometheus', version = '0.10.0-dev' }
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sc-utils = { path = '../../utils', version = '4.0.0-dev' }
serde = { features = ['derive'], version = '1.0' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-state-machine = { path = '../../../primitives/state-machine', version = '0.12.0' }
thiserror = '1.0.30'

[dev-dependencies]
sp-test-primitives = { path = '../../../primitives/test-primitives', version = '2.0.0' }
