[package]
name = 'pallet-contracts'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet for WASM contracts'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
bitflags = '1.3'
codec = { default-features = false, features = [
	'derive',
	'max-encoded-len',
], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
log = { default-features = false, version = '0.4' }
pallet-contracts-primitives = { default-features = false, path = 'common', version = '6.0.0' }
pallet-contracts-proc-macro = { path = 'proc-macro', version = '4.0.0-dev' }
rand = { default-features = false, optional = true, version = '0.8' }
rand_pcg = { optional = true, version = '0.3' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1' }
smallvec = { default-features = false, features = [
	'const_generics',
], version = '1' }
sp-core = { default-features = false, path = '../../primitives/core', version = '6.0.0' }
sp-io = { default-features = false, path = '../../primitives/io', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-sandbox = { default-features = false, path = '../../primitives/sandbox', version = '0.10.0-dev' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }
wasm-instrument = { default-features = false, version = '0.1' }
wasmi-validation = { default-features = false, version = '0.4' }

[dev-dependencies]
assert_matches = '1'
env_logger = '0.9'
hex-literal = '0.3'
pallet-balances = { path = '../balances', version = '4.0.0-dev' }
pallet-randomness-collective-flip = { path = '../randomness-collective-flip', version = '4.0.0-dev' }
pallet-timestamp = { path = '../timestamp', version = '4.0.0-dev' }
pallet-utility = { path = '../utility', version = '4.0.0-dev' }
pretty_assertions = '1'
sp-keystore = { path = '../../primitives/keystore', version = '0.12.0' }
wat = '1'

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'pallet-contracts-primitives/std',
	'pallet-contracts-proc-macro/full',
	'rand/std',
	'scale-info/std',
	'serde',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-sandbox/std',
	'sp-std/std',
	'wasm-instrument/std',
	'wasmi-validation/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'rand',
	'rand_pcg',
	'unstable-interface',
]
try-runtime = ['frame-support/try-runtime']
unstable-interface = []
