[package]
name = 'node-template'
version = '4.0.0-dev'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
homepage = 'https://substrate.io'
edition = '2021'
license = 'Unlicense'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
build = 'build.rs'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'node-template'

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
frame-benchmarking = { path = '../../../frame/benchmarking', version = '4.0.0-dev' }
frame-benchmarking-cli = { path = '../../../utils/frame/benchmarking-cli', version = '4.0.0-dev' }
frame-system = { path = '../../../frame/system', version = '4.0.0-dev' }
jsonrpc-core = '18.0.0'
node-template-runtime = { path = '../runtime', version = '4.0.0-dev' }
pallet-transaction-payment = { default-features = false, path = '../../../frame/transaction-payment', version = '4.0.0-dev' }
pallet-transaction-payment-rpc = { path = '../../../frame/transaction-payment/rpc/', version = '4.0.0-dev' }
sc-basic-authorship = { path = '../../../client/basic-authorship', version = '0.10.0-dev' }
sc-cli = { features = ['wasmtime'], path = '../../../client/cli', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api', version = '4.0.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-consensus-aura = { path = '../../../client/consensus/aura', version = '0.10.0-dev' }
sc-executor = { features = ['wasmtime'], path = '../../../client/executor', version = '0.10.0-dev' }
sc-finality-grandpa = { path = '../../../client/finality-grandpa', version = '0.10.0-dev' }
sc-keystore = { path = '../../../client/keystore', version = '4.0.0-dev' }
sc-rpc = { path = '../../../client/rpc', version = '4.0.0-dev' }
sc-rpc-api = { path = '../../../client/rpc-api', version = '0.10.0-dev' }
sc-service = { features = ['wasmtime'], path = '../../../client/service', version = '0.10.0-dev' }
sc-telemetry = { path = '../../../client/telemetry', version = '4.0.0-dev' }
sc-transaction-pool = { path = '../../../client/transaction-pool', version = '4.0.0-dev' }
sc-transaction-pool-api = { path = '../../../client/transaction-pool/api', version = '4.0.0-dev' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-block-builder = { path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-aura = { path = '../../../primitives/consensus/aura', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-finality-grandpa = { path = '../../../primitives/finality-grandpa', version = '4.0.0-dev' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-keyring = { path = '../../../primitives/keyring', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-timestamp = { path = '../../../primitives/timestamp', version = '4.0.0-dev' }
substrate-frame-rpc-system = { path = '../../../utils/frame/rpc/system', version = '4.0.0-dev' }
try-runtime-cli = { optional = true, path = '../../../utils/frame/try-runtime/cli', version = '0.10.0-dev' }

[build-dependencies]
substrate-build-script-utils = { version = '3.0.0', path = '../../../utils/build-script-utils' }

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
try-runtime = ['node-template-runtime/try-runtime', 'try-runtime-cli']
