[package]
name = 'node-bench'
version = '0.9.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Substrate node integration benchmarks.'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'

[dependencies]
clap = { version = '3.1.6', features = ['derive'] }
derive_more = '0.99.16'
fs_extra = '1'
futures = { version = '0.3.21', features = ['thread-pool'] }
hash-db = '0.15.2'
hex = '0.4.0'
kvdb = '0.11.0'
kvdb-rocksdb = '0.15.1'
lazy_static = '1.4.0'
log = '0.4.16'
node-primitives = { version = '2.0.0', path = '../primitives' }
node-runtime = { version = '3.0.0-dev', path = '../runtime' }
node-testing = { version = '3.0.0-dev', path = '../testing' }
parity-db = { version = '0.3' }
parity-util-mem = { version = '0.11.0', default-features = false, features = ['primitive-types'] }
rand = { version = '0.7.2', features = ['small_rng'] }
sc-basic-authorship = { version = '0.10.0-dev', path = '../../../client/basic-authorship' }
sc-client-api = { version = '4.0.0-dev', path = '../../../client/api/' }
sc-transaction-pool = { version = '4.0.0-dev', path = '../../../client/transaction-pool' }
sc-transaction-pool-api = { version = '4.0.0-dev', path = '../../../client/transaction-pool/api' }
serde = '1.0.136'
serde_json = '1.0.79'
sp-consensus = { version = '0.10.0-dev', path = '../../../primitives/consensus/common' }
sp-core = { version = '6.0.0', path = '../../../primitives/core' }
sp-inherents = { version = '4.0.0-dev', path = '../../../primitives/inherents' }
sp-runtime = { version = '6.0.0', path = '../../../primitives/runtime' }
sp-state-machine = { version = '0.12.0', path = '../../../primitives/state-machine' }
sp-timestamp = { version = '4.0.0-dev', default-features = false, path = '../../../primitives/timestamp' }
sp-tracing = { version = '5.0.0', path = '../../../primitives/tracing' }
sp-trie = { version = '6.0.0', path = '../../../primitives/trie' }
tempfile = '3.1.0'
