[package]
name = 'node-bench'
version = '0.9.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Substrate node integration benchmarks.'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
derive_more = '0.99.16'
fs_extra = '1'
futures = { features = ['thread-pool'], version = '0.3.21' }
hash-db = '0.15.2'
hex = '0.4.0'
kvdb = '0.11.0'
kvdb-rocksdb = '0.15.1'
lazy_static = '1.4.0'
log = '0.4.16'
node-primitives = { path = '../primitives', version = '2.0.0' }
node-runtime = { path = '../runtime', version = '3.0.0-dev' }
node-testing = { path = '../testing', version = '3.0.0-dev' }
parity-db = { version = '0.3' }
parity-util-mem = { default-features = false, features = ['primitive-types'], version = '0.11.0' }
rand = { features = ['small_rng'], version = '0.7.2' }
sc-basic-authorship = { path = '../../../client/basic-authorship', version = '0.10.0-dev' }
sc-client-api = { path = '../../../client/api/', version = '4.0.0-dev' }
sc-transaction-pool = { path = '../../../client/transaction-pool', version = '4.0.0-dev' }
sc-transaction-pool-api = { path = '../../../client/transaction-pool/api', version = '4.0.0-dev' }
serde = '1.0.136'
serde_json = '1.0.79'
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-state-machine = { path = '../../../primitives/state-machine', version = '0.12.0' }
sp-timestamp = { default-features = false, path = '../../../primitives/timestamp', version = '4.0.0-dev' }
sp-tracing = { path = '../../../primitives/tracing', version = '5.0.0' }
sp-trie = { path = '../../../primitives/trie', version = '6.0.0' }
tempfile = '3.1.0'
