[package]
name = 'frame-election-provider-solution-type'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'NPoS Solution Type'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = '1.1.3'
proc-macro2 = '1.0.37'
quote = '1.0'
syn = { features = ['full', 'visit'], version = '1.0.82' }

[dev-dependencies]
frame-election-provider-support = { path = '..', version = '4.0.0-dev' }
frame-support = { path = '../../support', version = '4.0.0-dev' }
parity-scale-codec = '3.0.0'
scale-info = '2.0.1'
sp-arithmetic = { path = '../../../primitives/arithmetic', version = '5.0.0' }
trybuild = '1.0.60'
