[package]
name = 'sc-consensus-uncles'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Generic uncle inclusion utilities for consensus'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sp-authorship = { path = '../../../primitives/authorship', version = '4.0.0-dev' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
thiserror = '1.0.30'
