[package]
name = 'sp-transaction-pool'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Transaction pool runtime facing API.'
documentation = 'https://docs.rs/sp-transaction-pool'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
sp-api = { default-features = false, path = '../api', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }

[features]
default = [ 'std' ]
std = [
	'sp-api/std',
	'sp-runtime/std',
]
