[package]
name = 'sc-consensus-babe'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'BABE consensus algorithm for substrate'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
documentation = 'https://docs.rs/sc-consensus-babe'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = '0.1.50'
codec = { features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
fork-tree = { path = '../../../utils/fork-tree', version = '3.0.0' }
futures = '0.3.21'
log = '0.4.16'
merlin = '2.0'
num-bigint = '0.2.3'
num-rational = '0.2.2'
num-traits = '0.2.8'
parking_lot = '0.12.0'
prometheus-endpoint = { package = 'substrate-prometheus-endpoint', path = '../../../utils/prometheus', version = '0.10.0-dev' }
rand = '0.7.2'
retain_mut = '0.1.4'
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sc-consensus = { path = '../../../client/consensus/common', version = '0.10.0-dev' }
sc-consensus-epochs = { path = '../epochs', version = '0.10.0-dev' }
sc-consensus-slots = { path = '../slots', version = '0.10.0-dev' }
sc-keystore = { path = '../../keystore', version = '4.0.0-dev' }
sc-telemetry = { path = '../../telemetry', version = '4.0.0-dev' }
schnorrkel = { features = ['preaudit_deprecated'], version = '0.9.1' }
serde = { features = ['derive'], version = '1.0.136' }
sp-api = { path = '../../../primitives/api', version = '4.0.0-dev' }
sp-application-crypto = { path = '../../../primitives/application-crypto', version = '6.0.0' }
sp-block-builder = { path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-consensus = { path = '../../../primitives/consensus/common', version = '0.10.0-dev' }
sp-consensus-babe = { path = '../../../primitives/consensus/babe', version = '0.10.0-dev' }
sp-consensus-slots = { path = '../../../primitives/consensus/slots', version = '0.10.0-dev' }
sp-consensus-vrf = { path = '../../../primitives/consensus/vrf', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-io = { path = '../../../primitives/io', version = '6.0.0' }
sp-keystore = { path = '../../../primitives/keystore', version = '0.12.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
sp-version = { path = '../../../primitives/version', version = '5.0.0' }
thiserror = '1.0'

[dev-dependencies]
rand_chacha = '0.2.2'
sc-block-builder = { path = '../../block-builder', version = '0.10.0-dev' }
sc-network = { path = '../../network', version = '0.10.0-dev' }
sc-network-test = { path = '../../network/test', version = '0.8.0' }
sp-timestamp = { path = '../../../primitives/timestamp', version = '4.0.0-dev' }
sp-tracing = { path = '../../../primitives/tracing', version = '5.0.0' }
substrate-test-runtime-client = { path = '../../../test-utils/runtime/client', version = '2.0.0' }
tempfile = '3.1.0'
