[package]
name = 'sp-npos-elections-fuzzer'
version = '2.0.0-alpha.5'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Fuzzer for phragmén implementation.'
documentation = 'https://docs.rs/sp-npos-elections-fuzzer'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
honggfuzz = '0.5'
rand = { features = ['std', 'small_rng'], version = '0.8' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-npos-elections = { path = '..', version = '4.0.0-dev' }
sp-runtime = { path = '../../runtime', version = '6.0.0' }

[[bin]]
name = 'reduce'
path = 'src/reduce.rs'

[[bin]]
name = 'phragmen_balancing'
path = 'src/phragmen_balancing.rs'

[[bin]]
name = 'phragmms_balancing'
path = 'src/phragmms_balancing.rs'

[[bin]]
name = 'phragmen_pjr'
path = 'src/phragmen_pjr.rs'
