[package]
name = 'sp-api'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Substrate runtime api primitives'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
hash-db = { optional = true, version = '0.15.2' }
log = { default-features = false, version = '0.4.16' }
sp-api-proc-macro = { path = 'proc-macro', version = '4.0.0-dev' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-state-machine = { optional = true, path = '../state-machine', version = '0.12.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
sp-version = { default-features = false, path = '../version', version = '5.0.0' }
thiserror = { optional = true, version = '1.0.30' }

[dev-dependencies]
sp-test-primitives = { path = '../test-primitives', version = '2.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'hash-db',
	'log/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-state-machine',
	'sp-std/std',
	'sp-version/std',
	'thiserror',
]
disable-logging = ['log/max_level_off']
