[package]
name = 'sp-api'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Substrate runtime api primitives'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }
hash-db = { version = '0.15.2', optional = true }
log = { version = '0.4.16', default-features = false }
sp-api-proc-macro = { version = '4.0.0-dev', path = 'proc-macro' }
sp-core = { version = '6.0.0', default-features = false, path = '../core' }
sp-runtime = { version = '6.0.0', default-features = false, path = '../runtime' }
sp-state-machine = { version = '0.12.0', optional = true, path = '../state-machine' }
sp-std = { version = '4.0.0', default-features = false, path = '../std' }
sp-version = { version = '5.0.0', default-features = false, path = '../version' }
thiserror = { version = '1.0.30', optional = true }

[dev-dependencies]
sp-test-primitives = { version = '2.0.0', path = '../test-primitives' }

[features]
default = ['std']
std = [
	'codec/std',
	'hash-db',
	'log/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-state-machine',
	'sp-std/std',
	'sp-version/std',
	'thiserror',
]
disable-logging = ['log/max_level_off']
