[package]
name = 'sp-consensus'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Common utilities for building and using consensus engines in substrate.'
documentation = 'https://docs.rs/sp-consensus/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
async-trait = '0.1.42'
codec = { features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
futures = { features = ['thread-pool'], version = '0.3.21' }
futures-timer = '3.0.1'
log = '0.4.16'
sp-core = { path = '../../core', version = '6.0.0' }
sp-inherents = { path = '../../inherents', version = '4.0.0-dev' }
sp-runtime = { path = '../../runtime', version = '6.0.0' }
sp-state-machine = { path = '../../state-machine', version = '0.12.0' }
sp-std = { path = '../../std', version = '4.0.0' }
sp-version = { path = '../../version', version = '5.0.0' }
thiserror = '1.0.30'

[dev-dependencies]
futures = '0.3.21'
sp-test-primitives = { path = '../../test-primitives', version = '2.0.0' }

[features]
default = []
