[package]
name = 'pallet-offences'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME offences pallet'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-support = { default-features = false, path = '../support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../system', version = '4.0.0-dev' }
log = { default-features = false, version = '0.4.16' }
pallet-balances = { default-features = false, path = '../balances', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { optional = true, version = '1.0.136' }
sp-runtime = { default-features = false, path = '../../primitives/runtime', version = '6.0.0' }
sp-staking = { default-features = false, path = '../../primitives/staking', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../primitives/std', version = '4.0.0' }

[dev-dependencies]
sp-core = { path = '../../primitives/core', version = '6.0.0' }
sp-io = { path = '../../primitives/io', version = '6.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'pallet-balances/std',
	'scale-info/std',
	'serde',
	'sp-runtime/std',
	'sp-staking/std',
	'sp-std/std',
]
runtime-benchmarks = []
try-runtime = ['frame-support/try-runtime']
