[package]
name = 'substrate-frame-cli'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'cli interface for FRAME'
documentation = 'https://docs.rs/substrate-frame-cli'
readme = 'README.md'

[dependencies]
clap = { features = ['derive'], version = '3.1.6' }
frame-support = { path = '../../../frame/support', version = '4.0.0-dev' }
frame-system = { path = '../../../frame/system', version = '4.0.0-dev' }
sc-cli = { path = '../../../client/cli', version = '0.10.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }

[features]
default = []
