[package]
name = 'sp-trie'
version = '6.0.0'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Patricia trie stuff using a parity-scale-codec node format'
repository = 'https://github.com/paritytech/substrate/'
license = 'Apache-2.0'
edition = '2021'
homepage = 'https://substrate.io'
documentation = 'https://docs.rs/sp-trie'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bench]]
name = 'bench'
harness = false

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
hash-db = { default-features = false, version = '0.15.2' }
memory-db = { default-features = false, version = '0.29.0' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
thiserror = { optional = true, version = '1.0.30' }
trie-db = { default-features = false, version = '0.23.1' }
trie-root = { default-features = false, version = '0.17.0' }

[dev-dependencies]
criterion = '0.3.3'
hex-literal = '0.3.4'
sp-runtime = { path = '../runtime', version = '6.0.0' }
trie-bench = '0.30.0'
trie-standardmap = '0.15.2'

[features]
default = ['std']
std = [
	'codec/std',
	'hash-db/std',
	'memory-db/std',
	'scale-info/std',
	'sp-core/std',
	'sp-std/std',
	'thiserror',
	'trie-db/std',
	'trie-root/std',
]
memory-tracker = []
