[package]
name = 'sp-finality-grandpa'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Primitives for GRANDPA integration, suitable for WASM compilation.'
documentation = 'https://docs.rs/sp-finality-grandpa'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
grandpa = { default-features = false, features = ['derive-codec'], package = 'finality-grandpa', version = '0.15.0' }
log = { optional = true, version = '0.4.16' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { features = ['derive'], optional = true, version = '1.0.136' }
sp-api = { default-features = false, path = '../api', version = '4.0.0-dev' }
sp-application-crypto = { default-features = false, path = '../application-crypto', version = '6.0.0' }
sp-core = { default-features = false, path = '../core', version = '6.0.0' }
sp-keystore = { default-features = false, optional = true, path = '../keystore', version = '0.12.0' }
sp-runtime = { default-features = false, path = '../runtime', version = '6.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }

[features]
default = ['std']
std = [
	'codec/std',
	'grandpa/std',
	'log',
	'scale-info/std',
	'serde',
	'sp-api/std',
	'sp-application-crypto/std',
	'sp-core/std',
	'sp-keystore',
	'sp-runtime/std',
	'sp-std/std',
]
