[package]
name = 'sc-finality-grandpa-rpc'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'RPC extensions for the GRANDPA finality gadget'
repository = 'https://github.com/paritytech/substrate/'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
readme = 'README.md'
homepage = 'https://substrate.io'

[dependencies]
finality-grandpa = { features = ['derive-codec'], version = '0.15.0' }
futures = '0.3.16'
jsonrpc-core = '18.0.0'
jsonrpc-core-client = '18.0.0'
jsonrpc-derive = '18.0.0'
jsonrpc-pubsub = '18.0.0'
log = '0.4.8'
parity-scale-codec = { features = ['derive'], version = '3.0.0' }
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sc-finality-grandpa = { path = '../', version = '0.10.0-dev' }
sc-rpc = { path = '../../rpc', version = '4.0.0-dev' }
serde = { features = ['derive'], version = '1.0.105' }
serde_json = '1.0.50'
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
thiserror = '1.0'

[dev-dependencies]
sc-block-builder = { path = '../../block-builder', version = '0.10.0-dev' }
sc-rpc = { features = [
	'test-helpers',
], path = '../../rpc', version = '4.0.0-dev' }
sp-core = { path = '../../../primitives/core', version = '6.0.0' }
sp-finality-grandpa = { path = '../../../primitives/finality-grandpa', version = '4.0.0-dev' }
sp-keyring = { path = '../../../primitives/keyring', version = '6.0.0' }
substrate-test-runtime-client = { path = '../../../test-utils/runtime/client', version = '2.0.0' }
