[package]
name = 'pallet-state-trie-migration'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'FRAME pallet migration of trie'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../benchmarking' }
frame-support = { default-features = false, path = '../support' }
frame-system = { default-features = false, path = '../system' }
log = { default-features = false, version = '0.4.16' }
remote-externalities = { optional = true, path = '../../utils/frame/remote-externalities' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
serde = { optional = true, version = '1.0.133' }
sp-core = { default-features = false, path = '../../primitives/core' }
sp-io = { default-features = false, path = '../../primitives/io' }
sp-runtime = { default-features = false, path = '../../primitives/runtime' }
sp-std = { default-features = false, path = '../../primitives/std' }
substrate-state-trie-migration-rpc = { optional = true, path = '../../utils/frame/rpc/state-trie-migration-rpc' }
thousands = { optional = true, version = '0.2.0' }
zstd = { default-features = false, optional = true, version = '0.10.0' }

[dev-dependencies]
pallet-balances = { path = '../balances' }
parking_lot = '0.12.0'
sp-tracing = { path = '../../primitives/tracing' }
tokio = { features = ['macros'], version = '1.10' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'log/std',
	'scale-info/std',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]
runtime-benchmarks = ['frame-benchmarking']
try-runtime = ['frame-support/try-runtime']
remote-test = [ 'remote-externalities', 'serde', 'std', 'substrate-state-trie-migration-rpc', 'thousands', 'zstd' ]
