[package]
name = 'substrate-test-runtime-transaction-pool'
version = '2.0.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
publish = false

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
futures = '0.3.21'
parking_lot = '0.12.0'
sc-transaction-pool = { path = '../../../client/transaction-pool', version = '4.0.0-dev' }
sc-transaction-pool-api = { path = '../../../client/transaction-pool/api', version = '4.0.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
substrate-test-runtime-client = { path = '../client', version = '2.0.0' }
thiserror = '1.0'
