[package]
name = 'sp-tracing'
version = '5.0.0'
license = 'Apache-2.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Instrumentation primitives and macros for Substrate.'
readme = 'README.md'

[package.metadata.docs.rs]
default-target = 'wasm32-unknown-unknown'
features = ['with-tracing']
targets = ['x86_64-unknown-linux-gnu', 'wasm32-unknown-unknown']

[dependencies]
codec = { default-features = false, features = [
	'derive',
], package = 'parity-scale-codec', version = '3.0.0' }
sp-std = { default-features = false, path = '../std', version = '4.0.0' }
tracing = { default-features = false, version = '0.1.29' }
tracing-core = { default-features = false, version = '0.1.26' }
tracing-subscriber = { features = [
	'tracing-log',
], optional = true, version = '0.2.25' }

[features]
default = ['std']
with-tracing = ['codec/derive', 'codec/full']
std = [
	'codec/std',
	'sp-std/std',
	'tracing-core/std',
	'tracing-subscriber',
	'tracing/std',
	'with-tracing',
]
