[package]
name = 'sp-tracing'
version = '5.0.0'
license = 'Apache-2.0'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Instrumentation primitives and macros for Substrate.'
readme = 'README.md'

[package.metadata.docs.rs]
default-target = 'wasm32-unknown-unknown'
features = ['with-tracing']
targets = ['x86_64-unknown-linux-gnu', 'wasm32-unknown-unknown']

[dependencies]
codec = { version = '3.0.0', package = 'parity-scale-codec', default-features = false, features = [
	'derive',
] }
sp-std = { version = '4.0.0', path = '../std', default-features = false }
tracing = { version = '0.1.29', default-features = false }
tracing-core = { version = '0.1.26', default-features = false }
tracing-subscriber = { version = '0.2.25', optional = true, features = [
	'tracing-log',
] }

[features]
default = ['std']
with-tracing = ['codec/derive', 'codec/full']
std = [
	'codec/std',
	'sp-std/std',
	'tracing-core/std',
	'tracing-subscriber',
	'tracing/std',
	'with-tracing',
]
