[package]
name = 'sc-executor-common'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'A set of common definitions that are needed for defining execution engines.'
documentation = 'https://docs.rs/sc-executor-common/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0' }
environmental = '1.1.3'
sc-allocator = { path = '../../allocator', version = '4.1.0-dev' }
sp-maybe-compressed-blob = { path = '../../../primitives/maybe-compressed-blob', version = '4.1.0-dev' }
sp-sandbox = { path = '../../../primitives/sandbox', version = '0.10.0-dev' }
sp-serializer = { path = '../../../primitives/serializer', version = '4.0.0-dev' }
sp-wasm-interface = { path = '../../../primitives/wasm-interface', version = '6.0.0' }
thiserror = '1.0.30'
wasm-instrument = '0.1'
wasmer = { features = ['singlepass'], optional = true, version = '2.2' }
wasmi = '0.9.1'

[features]
default = []
wasmer-sandbox = [
	'wasmer',
]
