[package]
name = 'generate-bags'
version = '4.0.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
edition = '2021'
license = 'Apache-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
description = 'Bag threshold generation script for pallet-bag-list'
readme = 'README.md'

[dependencies]
chrono = { version = '0.4.19' }
frame-election-provider-support = { version = '4.0.0-dev', path = '../../../frame/election-provider-support', features = ['runtime-benchmarks'] }
frame-support = { version = '4.0.0-dev', path = '../../../frame/support' }
frame-system = { version = '4.0.0-dev', path = '../../../frame/system' }
git2 = { version = '0.13.25', default-features = false }
num-format = { version = '0.4.0' }
pallet-staking = { version = '4.0.0-dev', path = '../../../frame/staking' }
sp-io = { version = '6.0.0', path = '../../../primitives/io' }
