[package]
name = 'sc-consensus-epochs'
version = '0.10.0-dev'
authors = ['Parity Technologies <admin@parity.io>']
description = 'Generic epochs-based utilities for consensus'
edition = '2021'
license = 'GPL-3.0-or-later WITH Classpath-exception-2.0'
homepage = 'https://substrate.io'
repository = 'https://github.com/paritytech/substrate/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
fork-tree = { path = '../../../utils/fork-tree', version = '3.0.0' }
sc-client-api = { path = '../../api', version = '4.0.0-dev' }
sc-consensus = { path = '../common', version = '0.10.0-dev' }
sp-blockchain = { path = '../../../primitives/blockchain', version = '4.0.0-dev' }
sp-runtime = { path = '../../../primitives/runtime', version = '6.0.0' }
