[package]
name = 'node-template-runtime'
version = '4.0.0-dev'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
homepage = 'https://substrate.io'
edition = '2021'
license = 'Unlicense'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, path = '../../../frame/benchmarking', version = '4.0.0-dev' }
frame-executive = { default-features = false, path = '../../../frame/executive', version = '4.0.0-dev' }
frame-support = { default-features = false, path = '../../../frame/support', version = '4.0.0-dev' }
frame-system = { default-features = false, path = '../../../frame/system', version = '4.0.0-dev' }
frame-system-benchmarking = { default-features = false, optional = true, path = '../../../frame/system/benchmarking', version = '4.0.0-dev' }
frame-system-rpc-runtime-api = { default-features = false, path = '../../../frame/system/rpc/runtime-api/', version = '4.0.0-dev' }
frame-try-runtime = { default-features = false, optional = true, path = '../../../frame/try-runtime', version = '0.10.0-dev' }
hex-literal = { optional = true, version = '0.3.4' }
pallet-aura = { default-features = false, path = '../../../frame/aura', version = '4.0.0-dev' }
pallet-balances = { default-features = false, path = '../../../frame/balances', version = '4.0.0-dev' }
pallet-grandpa = { default-features = false, path = '../../../frame/grandpa', version = '4.0.0-dev' }
pallet-randomness-collective-flip = { default-features = false, path = '../../../frame/randomness-collective-flip', version = '4.0.0-dev' }
pallet-sudo = { default-features = false, path = '../../../frame/sudo', version = '4.0.0-dev' }
pallet-template = { default-features = false, path = '../pallets/template', version = '4.0.0-dev' }
pallet-timestamp = { default-features = false, path = '../../../frame/timestamp', version = '4.0.0-dev' }
pallet-transaction-payment = { default-features = false, path = '../../../frame/transaction-payment', version = '4.0.0-dev' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, path = '../../../frame/transaction-payment/rpc/runtime-api/', version = '4.0.0-dev' }
scale-info = { default-features = false, features = ['derive'], version = '2.0.1' }
sp-api = { default-features = false, path = '../../../primitives/api', version = '4.0.0-dev' }
sp-block-builder = { default-features = false, path = '../../../primitives/block-builder', version = '4.0.0-dev' }
sp-consensus-aura = { default-features = false, path = '../../../primitives/consensus/aura', version = '0.10.0-dev' }
sp-core = { default-features = false, path = '../../../primitives/core', version = '6.0.0' }
sp-inherents = { default-features = false, path = '../../../primitives/inherents', version = '4.0.0-dev' }
sp-offchain = { default-features = false, path = '../../../primitives/offchain', version = '4.0.0-dev' }
sp-runtime = { default-features = false, path = '../../../primitives/runtime', version = '6.0.0' }
sp-session = { default-features = false, path = '../../../primitives/session', version = '4.0.0-dev' }
sp-std = { default-features = false, path = '../../../primitives/std', version = '4.0.0' }
sp-transaction-pool = { default-features = false, path = '../../../primitives/transaction-pool', version = '4.0.0-dev' }
sp-version = { default-features = false, path = '../../../primitives/version', version = '5.0.0' }

[build-dependencies]
substrate-wasm-builder = { version = '5.0.0-dev', path = '../../../utils/wasm-builder' }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-executive/std',
	'frame-support/std',
	'frame-system-rpc-runtime-api/std',
	'frame-system/std',
	'pallet-aura/std',
	'pallet-balances/std',
	'pallet-grandpa/std',
	'pallet-randomness-collective-flip/std',
	'pallet-sudo/std',
	'pallet-template/std',
	'pallet-timestamp/std',
	'pallet-transaction-payment-rpc-runtime-api/std',
	'pallet-transaction-payment/std',
	'scale-info/std',
	'sp-api/std',
	'sp-block-builder/std',
	'sp-consensus-aura/std',
	'sp-core/std',
	'sp-inherents/std',
	'sp-offchain/std',
	'sp-runtime/std',
	'sp-session/std',
	'sp-std/std',
	'sp-transaction-pool/std',
	'sp-version/std',
]
runtime-benchmarks = [
	'frame-benchmarking/runtime-benchmarks',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'hex-literal',
	'pallet-balances/runtime-benchmarks',
	'pallet-template/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'sp-runtime/runtime-benchmarks',
]
try-runtime = [
	'frame-executive/try-runtime',
	'frame-system/try-runtime',
	'frame-try-runtime',
	'pallet-balances/try-runtime',
	'pallet-grandpa/try-runtime',
	'pallet-randomness-collective-flip/try-runtime',
	'pallet-sudo/try-runtime',
	'pallet-timestamp/try-runtime',
	'pallet-transaction-payment/try-runtime',
]
